import type { NextRequest } from 'next/server';
import { Prisma } from '@prisma/client';
import { isDatabaseConfigured, prisma } from '@/lib/db';
import { jsonError, jsonOk, jsonPreflight } from '@/lib/api/response';
import { requireSellerApi } from '@/lib/auth/require-seller-api';
import { productUpdateSchema, parseProductImages } from '@/features/products/product-contract';
import { getProductService } from '@/server/infrastructure/registry';
import { ProductServiceError } from '@/server/services/product.service';
import { mapErrorToResponse } from '@/server/infrastructure/errors';
import { uploadPersistent, deletePersistent } from '@/lib/storage';
import { logger } from '@/lib/logger';

export const dynamic = 'force-dynamic';
function serializeProduct<T extends object>(row:T){const out={...row} as Record<string,unknown>;if(out.price!=null)out.price=Number(out.price);if(out.compareAtPrice!=null)out.compareAtPrice=Number(out.compareAtPrice);if(out.weightKg!=null)out.weightKg=Number(out.weightKg);out.images=parseProductImages(out.imagesJson);delete out.imagesJson;return out;}
async function validateBrand(brandId:string|null|undefined,sellerId:string,isAdmin:boolean){if(!brandId)return null;const rows=await prisma.$queryRaw<Array<{id:string;name:string;slug:string}>>(Prisma.sql`SELECT "id","name","slug" FROM "SellerBrand" WHERE "id"=${brandId} AND "isActive"=true ${isAdmin?Prisma.empty:Prisma.sql`AND "sellerId"=${sellerId}`} LIMIT 1`);return rows[0]??null;}
async function cleanupImages(urls:string[],productId:string,userId:string){for(const url of urls){try{await deletePersistent(url);}catch(err){logger.warn('seller.products.media_cleanup_failed',{productId,userId,url},err);}}}
export async function OPTIONS(){return jsonPreflight();}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const guard=await requireSellerApi();if(!guard.ok)return guard.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});let body:unknown;try{body=await req.json();}catch{return jsonError('invalid_json','Invalid JSON',{status:400});}const parsed=productUpdateSchema.safeParse(body);if(!parsed.success)return jsonError('invalid_body','Invalid product patch',{status:422,details:{issues:parsed.error.issues}});try{const svc=getProductService();const ownership=await svc.checkOwnership(id,guard.user.id,guard.user.role==='admin');if(ownership==='not_found')return jsonError('not_found','Product not found',{status:404});if(ownership==='forbidden')return jsonError('forbidden','You do not own this product',{status:403});const {slug:_ignoredSlug,brandId,...changes}=parsed.data;if(brandId!==undefined&&!(await validateBrand(brandId,guard.user.id,guard.user.role==='admin')))return jsonError('invalid_brand','برند انتخاب‌شده وجود ندارد یا فعال نیست.',{status:422});const updated=await svc.updateProduct(id,{...changes,brandId});const brandRows=await prisma.$queryRaw<Array<{brandId:string|null}>>(Prisma.sql`SELECT "brandId" FROM "Product" WHERE "id"=${id} LIMIT 1`);return jsonOk({...serializeProduct(updated),brandId:brandRows[0]?.brandId??null});}catch(err){if(err instanceof ProductServiceError)return jsonError(err.code,err.message,{status:err.httpStatus});logger.error('seller.product.update_failed',{productId:id,sellerId:guard.user.id},err);return mapErrorToResponse(err);}}
export async function DELETE(_req:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const guard=await requireSellerApi();if(!guard.ok)return guard.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});try{const svc=getProductService();const ownership=await svc.checkOwnership(id,guard.user.id,guard.user.role==='admin');if(ownership==='not_found')return jsonError('not_found','Product not found',{status:404});if(ownership==='forbidden')return jsonError('forbidden','You do not own this product',{status:403});const product=await prisma.product.findUnique({where:{id},select:{imagesJson:true}});const orderItemCount=await prisma.orderItem.count({where:{productId:id}});if(orderItemCount>0){await prisma.product.update({where:{id},data:{isActive:false,inStock:false}});logger.info('seller.product.deactivated_after_orders',{productId:id,sellerId:guard.user.id,orderItemCount});return jsonOk({deleted:false,deactivated:true,preservedOrderHistory:true});}await svc.deleteProduct(id);const media=parseProductImages(product?.imagesJson);await cleanupImages(media,id,guard.user.id);logger.info('seller.product.deleted',{productId:id,sellerId:guard.user.id,mediaCount:media.length});return jsonOk({deleted:true,deactivated:false,mediaCleanupAttempted:media.length});}catch(err){logger.error('seller.product.delete_failed',{productId:id,sellerId:guard.user.id},err);return mapErrorToResponse(err);}}
