'use client';

import * as React from 'react';
import { CalendarClock, Eye, ImagePlus, Megaphone, Pencil, Plus, Save, Trash2, Upload, X } from 'lucide-react';

const placements = [
  { value: 'HOME_HERO', label: 'هیرو اصلی صفحه خانه', hint: 'بنر اصلی بالای صفحه' },
  { value: 'HOME_PROMO_1', label: 'بنر تبلیغاتی ۱', hint: 'کمپین تبلیغاتی اول' },
  { value: 'HOME_PROMO_2', label: 'بنر تبلیغاتی ۲', hint: 'کمپین تبلیغاتی دوم' },
  { value: 'HOME_MID', label: 'بنر میانی', hint: 'بین بخش‌های محتوایی خانه' },
  { value: 'HOME_CATEGORY', label: 'بنر دسته‌بندی‌ها', hint: 'کنار یا بالای دسته‌ها' },
  { value: 'HOME_SELLER', label: 'فراخوان فروشنده', hint: 'جذب فروشندگان جدید' },
] as const;

type Banner = {
  id: string; key: string; placement: string; title?: string | null; subtitle?: string | null; ctaLabel?: string | null; href?: string | null;
  desktopImageUrl: string; mobileImageUrl?: string | null; startAt?: string | null; endAt?: string | null; sortOrder: number; autoSlide: boolean; durationMs: number; isActive: boolean;
};
type Draft = Omit<Banner, 'id'> & { id?: string };
const emptyDraft: Draft = { key: 'home-hero-1', placement: 'HOME_HERO', title: '', subtitle: '', ctaLabel: '', href: '/shop', desktopImageUrl: '', mobileImageUrl: '', startAt: '', endAt: '', sortOrder: 0, autoSlide: true, durationMs: 5000, isActive: true };
const inputClass = 'h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10';

export function BannerManager() {
  const [items, setItems] = React.useState<Banner[]>([]); const [draft, setDraft] = React.useState<Draft>(emptyDraft); const [status, setStatus] = React.useState('');
  const [loading, setLoading] = React.useState(true); const [saving, setSaving] = React.useState(false); const [uploading, setUploading] = React.useState<'desktop' | 'mobile' | null>(null);
  async function load() { setLoading(true); try { const response = await fetch('/api/admin/banners', { cache: 'no-store' }); const body = await response.json(); setItems(Array.isArray(body?.data) ? body.data : []); } catch { setStatus('بارگذاری بنرها ناموفق بود.'); } finally { setLoading(false); } }
  React.useEffect(() => { void load(); }, []);
  async function uploadImage(kind: 'desktop' | 'mobile', file: File | undefined) {
    if (!file) return;
    if (!file.type.startsWith('image/')) { setStatus('فقط فایل تصویری مجاز است؛ ویدیو و فایل غیرتصویری قابل آپلود نیست.'); return; }
    if (file.size <= 0 || file.size > 10 * 1024 * 1024) { setStatus('حداکثر حجم تصویر ۱۰ مگابایت است.'); return; }
    setUploading(kind);
    try { const form = new FormData(); form.set('file', file); const response = await fetch('/api/admin/media', { method: 'POST', body: form }); const body = await response.json(); if (!response.ok || !body?.ok || !body?.data?.url) throw new Error('upload_failed'); setDraft((current) => ({ ...current, [kind === 'desktop' ? 'desktopImageUrl' : 'mobileImageUrl']: body.data.url })); setStatus(kind === 'desktop' ? 'تصویر دسکتاپ آماده شد.' : 'تصویر موبایل آماده شد.'); }
    catch { setStatus('آپلود تصویر ناموفق بود.'); } finally { setUploading(null); }
  }
  function edit(item: Banner) { setDraft({ id: item.id, key: item.key, placement: item.placement, title: item.title ?? '', subtitle: item.subtitle ?? '', ctaLabel: item.ctaLabel ?? '', href: item.href ?? '', desktopImageUrl: item.desktopImageUrl ?? '', mobileImageUrl: item.mobileImageUrl ?? '', startAt: item.startAt ? new Date(item.startAt).toISOString().slice(0, 16) : '', endAt: item.endAt ? new Date(item.endAt).toISOString().slice(0, 16) : '', sortOrder: Number(item.sortOrder ?? 0), autoSlide: Boolean(item.autoSlide ?? true), durationMs: Number(item.durationMs ?? 5000), isActive: Boolean(item.isActive ?? true) }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function save() { if (!draft.key.trim()) { setStatus('کلید بنر الزامی است.'); return; } if (!draft.desktopImageUrl) { setStatus('تصویر دسکتاپ را انتخاب کنید.'); return; } if (draft.durationMs < 1500 || draft.durationMs > 30000) { setStatus('مدت اسلاید باید بین ۱۵۰۰ تا ۳۰۰۰۰ میلی‌ثانیه باشد.'); return; } setSaving(true); setStatus('در حال ذخیره بنر…'); try { const payload = { ...draft, startAt: draft.startAt ? new Date(draft.startAt).toISOString() : null, endAt: draft.endAt ? new Date(draft.endAt).toISOString() : null }; const response = await fetch('/api/admin/banners', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.ok) throw new Error(body?.error?.message ?? 'save_failed'); setDraft(emptyDraft); setStatus('بنر با موفقیت ذخیره شد.'); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : 'ذخیره بنر ناموفق بود.'); } finally { setSaving(false); } }
  async function remove(id: string) { if (!confirm('این بنر حذف شود؟')) return; const response = await fetch(`/api/admin/banners?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); if (!response.ok) { setStatus('حذف بنر ناموفق بود.'); return; } if (draft.id === id) setDraft(emptyDraft); setStatus('بنر حذف شد.'); await load(); }
  const activeCount = items.filter((item) => item.isActive).length; const placementLabel = (value: string) => placements.find((item) => item.value === value)?.label ?? value;
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-3"><Stat label="کل بنرها" value={items.length} icon={<Megaphone className="h-4 w-4" />} /><Stat label="بنر فعال" value={activeCount} icon={<Eye className="h-4 w-4" />} /><Stat label="جایگاه‌ها" value={placements.length} icon={<ImagePlus className="h-4 w-4" />} /></div>
    <section className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold text-primary">تنها محل تنظیم بنرهای صفحه اول</p><h2 className="mt-1 text-xl font-black">{draft.id ? 'ویرایش بنر' : 'افزودن بنر جدید'}</h2><p className="mt-1 text-xs leading-6 text-muted-foreground">تمام جایگاه، متن، تصویر، زمان‌بندی و وضعیت نمایش یکجا مدیریت می‌شود.</p></div>{draft.id ? <button type="button" onClick={() => setDraft(emptyDraft)} className="inline-flex items-center gap-2 self-start rounded-xl border border-border px-3 py-2 text-xs font-bold hover:bg-muted"><X className="h-4 w-4" /> انصراف از ویرایش</button> : null}</div>
      <div className="mt-6 grid gap-5 lg:grid-cols-2"><div className="space-y-4"><Field label="کلید یکتا"><input value={draft.key} onChange={(e) => setDraft({ ...draft, key: e.target.value })} className={inputClass} placeholder="home-hero-1" /></Field><Field label="جایگاه نمایش"><select value={draft.placement} onChange={(e) => setDraft({ ...draft, placement: e.target.value })} className={inputClass}>{placements.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="اولویت"><input type="number" min={0} max={10000} value={draft.sortOrder} onChange={(e) => setDraft({ ...draft, sortOrder: Number(e.target.value) || 0 })} className={inputClass} /></Field><Field label="مدت هر اسلاید (ms)"><input type="number" min={1500} max={30000} value={draft.durationMs} onChange={(e) => setDraft({ ...draft, durationMs: Number(e.target.value) || 5000 })} className={inputClass} /></Field></div><label className="flex h-11 items-center gap-3 rounded-xl border border-input px-3 text-sm font-semibold"><input type="checkbox" checked={draft.isActive} onChange={(e) => setDraft({ ...draft, isActive: e.target.checked })} className="h-4 w-4" /> بنر فعال باشد</label><label className="flex h-11 items-center gap-3 rounded-xl border border-input px-3 text-sm font-semibold"><input type="checkbox" checked={draft.autoSlide} onChange={(e) => setDraft({ ...draft, autoSlide: e.target.checked })} className="h-4 w-4" /> پخش خودکار اسلایدها</label></div><div className="space-y-4"><Field label="عنوان"><input value={draft.title ?? ''} onChange={(e) => setDraft({ ...draft, title: e.target.value })} className={inputClass} /></Field><Field label="زیرعنوان"><textarea value={draft.subtitle ?? ''} onChange={(e) => setDraft({ ...draft, subtitle: e.target.value })} rows={3} className={inputClass + ' h-auto py-3 resize-none'} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="متن دکمه"><input value={draft.ctaLabel ?? ''} onChange={(e) => setDraft({ ...draft, ctaLabel: e.target.value })} className={inputClass} /></Field><Field label="مسیر دکمه"><input dir="ltr" value={draft.href ?? ''} onChange={(e) => setDraft({ ...draft, href: e.target.value })} className={inputClass} placeholder="/shop" /></Field></div></div></div>
      <div className="mt-6 grid gap-4 border-t border-border pt-6 sm:grid-cols-2"><UploadBox title="تصویر دسکتاپ" required value={draft.desktopImageUrl} uploading={uploading === 'desktop'} onFile={(file) => void uploadImage('desktop', file)} /><UploadBox title="تصویر موبایل" value={draft.mobileImageUrl} uploading={uploading === 'mobile'} onFile={(file) => void uploadImage('mobile', file)} /></div>
      <div className="mt-6 grid gap-4 border-t border-border pt-6 sm:grid-cols-2"><Field label="شروع نمایش"><input type="datetime-local" value={draft.startAt ?? ''} onChange={(e) => setDraft({ ...draft, startAt: e.target.value })} className={inputClass} /></Field><Field label="پایان نمایش"><input type="datetime-local" value={draft.endAt ?? ''} onChange={(e) => setDraft({ ...draft, endAt: e.target.value })} className={inputClass} /></Field></div>
      <div className="mt-6 flex flex-wrap items-center gap-3"><button type="button" disabled={saving || Boolean(uploading)} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-black text-primary-foreground disabled:cursor-not-allowed disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'در حال ذخیره…' : draft.id ? 'ذخیره تغییرات' : 'ایجاد بنر'}</button>{status ? <span className="text-xs font-semibold text-muted-foreground">{status}</span> : null}</div>
    </section>
    <section className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">فهرست بنرهای صفحه اول</h2><p className="mt-1 text-xs text-muted-foreground">ویرایش و حذف همه بنرها از همین صفحه انجام می‌شود.</p></div><span className="rounded-full bg-muted px-3 py-1.5 text-xs font-bold">{loading ? '…' : items.length} بنر</span></div><div className="mt-5 space-y-3">{items.map((item) => <article key={item.id} className="flex flex-col gap-4 rounded-2xl border border-border bg-background p-4 md:flex-row md:items-center"><div className="flex h-24 w-full shrink-0 overflow-hidden rounded-2xl bg-muted md:w-40"><img src={item.desktopImageUrl} alt="" className="h-full w-full object-cover" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-black">{item.title || item.key}</span><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold">{placementLabel(item.placement)}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.isActive ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : 'bg-muted text-muted-foreground'}`}>{item.isActive ? 'فعال' : 'غیرفعال'}</span></div><p className="mt-2 truncate text-xs text-muted-foreground">{item.subtitle || 'بدون زیرعنوان'} · اولویت {item.sortOrder}</p></div><div className="flex shrink-0 items-center gap-2"><button type="button" onClick={() => edit(item)} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-bold hover:bg-muted"><Pencil className="h-4 w-4" /> ویرایش</button><button type="button" onClick={() => void remove(item.id)} className="inline-flex h-9 w-9 items-center justify-center rounded-xl border border-border text-destructive hover:bg-destructive/10" aria-label="حذف بنر"><Trash2 className="h-4 w-4" /></button></div></article>)}{!loading && items.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">هنوز بنری ثبت نشده است.</div> : null}</div></section>
  </div>;
}
function Stat({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-muted-foreground">{label}</span><span className="text-primary">{icon}</span></div><p className="mt-2 text-2xl font-black">{value}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-black">{label}</span>{children}</label>; }
function UploadBox({ title, required, value, uploading, onFile }: { title: string; required?: boolean; value?: string | null; uploading: boolean; onFile: (file: File | undefined) => void }) { const ref = React.useRef<HTMLInputElement>(null); return <div><div className="mb-1.5 text-xs font-black">{title}{required ? ' *' : ''}</div><button type="button" onClick={() => ref.current?.click()} disabled={uploading} className="group relative flex h-44 w-full items-center justify-center overflow-hidden rounded-2xl border border-dashed border-border bg-muted/20 disabled:opacity-60">{value ? <img src={value} alt="" className="h-full w-full object-cover" /> : <div className="flex flex-col items-center gap-2 text-muted-foreground"><ImagePlus className="h-7 w-7" /><span className="text-xs font-semibold">برای آپلود کلیک کنید</span></div>}<span className="absolute inset-x-4 bottom-3 flex items-center justify-center gap-2 rounded-xl bg-black/60 px-3 py-2 text-xs font-bold text-white opacity-0 transition group-hover:opacity-100"><Upload className="h-4 w-4" />{uploading ? 'در حال آپلود…' : value ? 'تغییر تصویر' : 'انتخاب تصویر'}</span></button><input ref={ref} type="file" accept="image/*" className="hidden" onChange={(e) => { onFile(e.target.files?.[0]); e.currentTarget.value = ''; }} /></div>; }
