'use client';

import * as React from 'react';
import { Link } from '@/i18n/routing';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { CategoryKey, ProductSummary } from '@/types';
import { MarketplaceProductCard } from '@/components/marketplace-product-card';
export interface SliderProduct { id: string; name: string; slug: string; price: number; comparePrice?: number | null; images?: Array<{ url: string }>; badge?: string; rating?: number; reviewCount?: number; salesCount?: number; viewCount?: number; categoryKey?: CategoryKey; category?: { name: string }; sellerId?: string | null; sellerShopName?: string | null; sellerWhatsapp?: string; region?: string; inStock?: boolean; }
interface ProductSliderSectionProps { title: string; subtitle?: string; viewAllHref?: string; accentColor?: string; products: SliderProduct[]; locale?: string; currency?: string; skeleton?: boolean; }
export function SkeletonCard() { return <div className="w-[calc((100vw-2.75rem)/2)] max-w-[204px] flex-none overflow-hidden rounded-2xl border border-rose-100 bg-white/80 shadow-sm dark:border-rose-950/40 dark:bg-card sm:w-[188px] md:w-[204px]" aria-hidden="true"><div className="aspect-[4/3] animate-pulse bg-rose-100/60 dark:bg-muted" /><div className="space-y-2 p-2.5 sm:p-3"><div className="h-2 w-16 animate-pulse rounded bg-muted" /><div className="h-3 w-full animate-pulse rounded bg-muted" /><div className="h-3 w-3/4 animate-pulse rounded bg-muted" /><div className="h-7 w-20 animate-pulse rounded-full bg-muted" /></div></div>; }
function toProductSummary(product: SliderProduct): ProductSummary { return { id: product.id, name: product.name, slug: product.slug, shortDescription: '', categoryKey: product.categoryKey ?? 'digital', price: product.price, currency: 'AFN', badge: product.badge as ProductSummary['badge'], region: product.region ?? 'افغانستان', images: (product.images ?? []).map((image) => ({ src: image.url, alt: product.name })), inStock: product.inStock !== false, sellerId: product.sellerId, sellerShopName: product.sellerShopName, sellerWhatsapp: product.sellerWhatsapp, averageRating: product.rating, reviewCount: product.reviewCount, salesCount: product.salesCount, viewCount: product.viewCount, comparePrice: product.comparePrice }; }
export function ProductSliderSection({ title, subtitle, viewAllHref, accentColor = 'bg-rose-600', products, locale = 'fa', currency = 'AFN', skeleton = false }: ProductSliderSectionProps) {
  const trackRef = React.useRef<HTMLDivElement>(null); const scroll = (dir: 1 | -1) => trackRef.current?.scrollBy({ left: dir * 520, behavior: 'smooth' }); const allLabel = locale === 'en' ? 'View all' : locale === 'ps' ? 'ټول' : 'همه'; if (products.length === 0 && !skeleton) return null;
  return <section className="border-y border-rose-200/60 bg-gradient-to-r from-rose-50 via-pink-50/70 to-white py-4 sm:py-6 dark:border-rose-950/40 dark:from-rose-950/20 dark:via-pink-950/10 dark:to-background" aria-label={title || undefined}><div className="mx-auto max-w-screen-xl px-3 sm:px-6"><div className="mb-3 flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2">{title && <span className={cn('h-6 w-1 rounded-full', accentColor)} />}<div className="min-w-0">{title && <h2 className="truncate text-sm font-black tracking-tight sm:text-base">{title}</h2>}{subtitle && <p className="mt-0.5 line-clamp-1 text-[10px] text-muted-foreground sm:text-[11px]">{subtitle}</p>}</div></div><div className="flex shrink-0 items-center gap-1.5"><button type="button" onClick={() => scroll(-1)} aria-label={locale === 'en' ? 'Previous products' : locale === 'ps' ? 'مخکني محصولات' : 'محصولات قبلی'} className="flex h-8 w-8 items-center justify-center rounded-full border border-rose-200 bg-white/80 text-muted-foreground shadow-sm transition-colors hover:bg-white hover:text-foreground dark:border-rose-950/50 dark:bg-card"><ChevronRight className="h-4 w-4 rtl:rotate-180" /></button><button type="button" onClick={() => scroll(1)} aria-label={locale === 'en' ? 'Next products' : locale === 'ps' ? 'راتلونکي محصولات' : 'محصولات بعدی'} className="flex h-8 w-8 items-center justify-center rounded-full border border-rose-200 bg-white/80 text-muted-foreground shadow-sm transition-colors hover:bg-white hover:text-foreground dark:border-rose-950/50 dark:bg-card"><ChevronLeft className="h-4 w-4 rtl:rotate-180" /></button>{viewAllHref && <Link href={viewAllHref as never} className="rounded-full border border-rose-200 bg-white/80 px-3 py-1.5 text-[10px] font-bold shadow-sm transition-colors hover:bg-white sm:text-[11px] dark:border-rose-950/50 dark:bg-card">{allLabel}</Link>}</div></div><div ref={trackRef} className="flex snap-x snap-mandatory gap-2.5 overflow-x-auto pb-1 no-scrollbar" dir={locale === 'en' ? 'ltr' : 'rtl'}>{skeleton ? Array.from({ length: 6 }).map((_, i) => <SkeletonCard key={i} />) : products.map((product) => <div key={product.id} className="snap-start"><MarketplaceProductCard product={toProductSummary(product)} locale={locale} currency={currency} view="rail" /></div>)}</div></div></section>;
}
