'use client';
import * as React from 'react';
import { toast } from 'sonner';
import { X, Upload, Star, ImagePlus, GripVertical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { isProductImageMimeType, PRODUCT_MAX_IMAGE_BYTES, PRODUCT_MAX_IMAGES } from '@/features/products/product-contract';
interface Props{productId:string;initial:string[];initialPrimaryIndex?:number}
function fileToDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result??''));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
export function ProductImagesEditor({productId,initial,initialPrimaryIndex=0}:Props){const[images,setImages]=React.useState(initial);const[primaryIndex,setPrimaryIndex]=React.useState(Math.max(0,Math.min(initialPrimaryIndex,Math.max(initial.length-1,0))));const[busy,setBusy]=React.useState(false);const[dragIndex,setDragIndex]=React.useState<number|null>(null);const inputRef=React.useRef<HTMLInputElement>(null);async function savePatch(payload:{images?:string[];primaryImageIndex?:number}){const res=await fetch(`/api/seller/products/${productId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});const body=await res.json().catch(()=>null);if(!res.ok||!body?.ok)throw new Error(body?.error?.message??'ذخیره تصویر ناموفق بود');return body}
async function onFiles(files:FileList|null){if(!files?.length||busy)return;const remaining=PRODUCT_MAX_IMAGES-images.length;if(remaining<=0)return toast.error(`حداکثر ${PRODUCT_MAX_IMAGES} تصویر مجاز است`);const list=Array.from(files).slice(0,remaining);setBusy(true);try{const results=await Promise.all(list.map(async file=>{if(!isProductImageMimeType(file.type)||file.size<=0||file.size>PRODUCT_MAX_IMAGE_BYTES){toast.error(`${file.name}: فرمت یا حجم تصویر نامعتبر است`);return null}const dataUrl=await fileToDataUrl(file);const res=await fetch(`/api/seller/products/${productId}/images`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({dataUrl,alt:file.name})});const body=await res.json().catch(()=>null);if(!res.ok||!body?.ok||typeof body?.data?.url!=='string'){toast.error(body?.error?.message??`${file.name}: آپلود ناموفق`);return null}return body.data.url as string}));const added=results.filter((url):url is string=>Boolean(url));if(added.length){setImages(prev=>[...prev,...added]);toast.success(`${added.length} تصویر افزوده شد`)}}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
async function onRemove(url:string,idx:number){setBusy(true);try{const res=await fetch(`/api/seller/products/${productId}/images`,{method:'DELETE',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({url})});const body=await res.json().catch(()=>null);if(!res.ok||!body?.ok)throw new Error(body?.error?.message??'حذف تصویر ناموفق بود');const next=images.filter(item=>item!==url);const nextPrimary=next.length===0?0:idx===primaryIndex?0:idx<primaryIndex?primaryIndex-1:Math.min(primaryIndex,next.length-1);setImages(next);setPrimaryIndex(nextPrimary);toast.success('تصویر حذف شد')}catch(error){toast.error(error instanceof Error?error.message:'حذف تصویر ناموفق بود')}finally{setBusy(false)}}
async function onSetPrimary(idx:number){const previous=primaryIndex;setPrimaryIndex(idx);setBusy(true);try{await savePatch({primaryImageIndex:idx});toast.success('تصویر اصلی تنظیم شد')}catch(error){setPrimaryIndex(previous);toast.error(error instanceof Error?error.message:'ذخیره تصویر اصلی ناموفق بود')}finally{setBusy(false)}}
async function onDrop(target:number){if(dragIndex==null||dragIndex===target||busy)return;const from=dragIndex,before=images,beforePrimary=primaryIndex,primaryUrl=images[primaryIndex],next=[...images];const[moved]=next.splice(from,1);if(!moved)return;next.splice(from<target?target-1:target,0,moved);const nextPrimary=primaryUrl?Math.max(0,next.indexOf(primaryUrl)):0;setImages(next);setPrimaryIndex(nextPrimary);setDragIndex(null);setBusy(true);try{await savePatch({images:next,primaryImageIndex:nextPrimary});toast.success('ترتیب تصاویر ذخیره شد')}catch(error){setImages(before);setPrimaryIndex(beforePrimary);toast.error(error instanceof Error?error.message:'ترتیب تصاویر ذخیره نشد')}finally{setBusy(false)}}
return <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><input ref={inputRef} type="file" accept="image/*" multiple className="hidden" onChange={e=>{void onFiles(e.target.files)}}/><Button type="button" variant="outline" size="sm" onClick={()=>inputRef.current?.click()} disabled={busy||images.length>=PRODUCT_MAX_IMAGES}><Upload className="h-4 w-4"/>{busy?'در حال پردازش…':'افزودن تصویر'}</Button><span className="text-xs text-muted-foreground">حداکثر ۲۰ مگابایت — هر فرمت تصویری — {images.length}/{PRODUCT_MAX_IMAGES} تصویر</span></div><ul className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">{images.map((src,idx)=><li key={src} draggable={!busy} onDragStart={()=>setDragIndex(idx)} onDragOver={e=>e.preventDefault()} onDrop={()=>void onDrop(idx)} onDragEnd={()=>setDragIndex(null)} className={`group relative overflow-hidden rounded-xl border-2 ${idx===primaryIndex?'border-primary shadow-md':'border-border'}`}><img src={src} alt={`تصویر ${idx+1}`} className="aspect-square w-full object-cover" loading="lazy"/><div className="absolute start-1 bottom-1 rounded-full bg-black/60 px-1.5 py-0.5 text-[10px] text-white"><GripVertical className="inline h-3 w-3"/>{idx+1}</div>{idx===primaryIndex&&<div className="absolute start-1 top-1 flex items-center gap-1 rounded-full bg-primary px-1.5 py-0.5 text-[10px] font-bold text-white"><Star className="h-2.5 w-2.5 fill-white"/>اصلی</div>}<div className="absolute inset-0 flex items-center justify-center gap-2 bg-black/60 opacity-0 transition group-hover:opacity-100">{idx!==primaryIndex&&<button type="button" onClick={()=>void onSetPrimary(idx)} disabled={busy} className="rounded-full bg-primary px-2.5 py-1.5 text-[11px] font-bold text-white">تصویر اصلی</button>}<button type="button" onClick={()=>void onRemove(src,idx)} disabled={busy} className="flex h-8 w-8 items-center justify-center rounded-full bg-black/70 text-white" aria-label="حذف تصویر"><X className="h-3.5 w-3.5"/></button></div></li>)}{images.length<1&&<li onClick={()=>inputRef.current?.click()} className="flex aspect-square cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-border text-muted-foreground"><ImagePlus className="h-6 w-6"/><span className="text-xs">انتخاب تصویر</span></li>}</ul></div>}
