'use client';
import * as React from 'react';
import Image from 'next/image';
import { toast } from 'sonner';
import { Check, Package, Search, X } from 'lucide-react';
interface Brand { id:string; name:string; logoUrl?:string|null }
interface Product { id:string; name:string; brandId?:string|null; images?:string[]; price?:number|string }
export function SellerBrandManager(){
 const [brand,setBrand]=React.useState<Brand|null>(null); const [products,setProducts]=React.useState<Product[]>([]); const [query,setQuery]=React.useState(''); const [loading,setLoading]=React.useState(true); const [busyId,setBusyId]=React.useState<string|null>(null);
 const load=React.useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/seller/brand',{credentials:'include',cache:'no-store'}),fetch('/api/seller/products?page=1&pageSize=50',{credentials:'include',cache:'no-store'})]);const aj=await a.json();const bj=await b.json();if(!a.ok||!aj?.ok)throw new Error(aj?.error?.message??'برند بارگذاری نشد.');if(!b.ok||!bj?.ok)throw new Error(bj?.error?.message??'محصولات بارگذاری نشدند.');setBrand({id:String(aj.data.id),name:String(aj.data.name??'برند من'),logoUrl:aj.data.logoUrl??null});setProducts(Array.isArray(bj.data)?bj.data:[]);}catch(e){toast.error(e instanceof Error?e.message:'بارگذاری برند ناموفق بود.')}finally{setLoading(false)}},[]);
 React.useEffect(()=>{void load()},[load]);
 async function toggle(p:Product){if(!brand)return;setBusyId(p.id);const brandId=p.brandId===brand.id?null:brand.id;try{const r=await fetch(`/api/seller/products/${p.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({brandId})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error?.message??'تغییر محصول ناموفق بود.');setProducts(x=>x.map(v=>v.id===p.id?{...v,brandId}:v));toast.success(brandId?'محصول به برند اضافه شد.':'محصول از برند خارج شد.')}catch(e){toast.error(e instanceof Error?e.message:'تغییر محصول ناموفق بود.')}finally{setBusyId(null)}}
 if(loading)return <div className="flex justify-center py-16"><span className="h-7 w-7 animate-spin rounded-full border-2 border-primary border-t-transparent"/></div>; if(!brand)return null; const filtered=products.filter(p=>p.name.toLowerCase().includes(query.trim().toLowerCase())); const assigned=products.filter(p=>p.brandId===brand.id).length;
 return <section className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Package className="h-5 w-5 text-primary"/><h2 className="text-base font-black">محصولات برند</h2></div><p className="mt-1 text-xs text-muted-foreground">هر محصول فروشگاه را انتخاب کنید تا در صفحه برند نمایش داده شود.</p></div><div className="rounded-full bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary">{assigned} محصول از {products.length}</div></header><div className="relative mb-4"><Search className="absolute end-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجوی محصول…" className="h-11 w-full rounded-2xl border border-input bg-background pe-10 ps-3.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15"/></div><div className="space-y-2">{filtered.length===0?<div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">محصولی پیدا نشد.</div>:filtered.map(p=>{const selected=p.brandId===brand.id;const img=p.images?.[0];return <div key={p.id} className={`flex items-center gap-3 rounded-2xl border p-3 ${selected?'border-primary/30 bg-primary/5':'border-border bg-background'}`}><div className="relative h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-muted">{img?<Image src={img} alt="" fill unoptimized className="object-cover"/>:<Package className="absolute inset-0 m-auto h-5 w-5 text-muted-foreground"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{p.name}</p>{p.price!=null&&<p className="mt-1 text-xs text-muted-foreground">{Number(p.price).toLocaleString('fa-AF')} افغانی</p>}</div><button type="button" onClick={()=>void toggle(p)} disabled={busyId===p.id} aria-pressed={selected} className={`flex h-10 items-center justify-center gap-1.5 rounded-xl px-3 text-xs font-bold ${selected?'bg-primary text-primary-foreground':'border border-border bg-background hover:border-primary hover:text-primary'}`}>{selected?<><Check className="h-4 w-4"/>داخل برند</>:<><X className="h-4 w-4"/>افزودن</>}</button></div>})}</div></section>;
}
