import type { NextRequest } from 'next/server';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import { jsonError, jsonOk, jsonPreflight } from '@/lib/api/response';
import { requireSellerApi } from '@/lib/auth/require-seller-api';

export const dynamic = 'force-dynamic';
const phone=z.string().trim().regex(/^[0-9+\-\s]{6,20}$/,'Invalid phone number');
const patchSchema=z.object({sellerShopName:z.string().trim().min(2).max(120).optional(),sellerBio:z.string().trim().max(1000).optional().nullable(),sellerLogoUrl:z.string().max(500).optional().nullable(),sellerBannerUrl:z.string().max(500).optional().nullable(),sellerWhatsapp:phone.optional().nullable(),sellerContactEmail:z.string().email().max(200).optional().nullable(),sellerContactPhone:phone.optional().nullable(),sellerAddress:z.string().trim().max(300).optional().nullable(),sellerCity:z.string().trim().max(120).optional().nullable(),sellerCountry:z.string().trim().max(120).optional().nullable(),sellerBankAccountNumber:z.string().trim().max(100).optional().nullable(),sellerBankAccountName:z.string().trim().max(200).optional().nullable(),sellerBankName:z.string().trim().max(120).optional().nullable(),sellerAtomaPay:z.string().trim().max(200).optional().nullable(),sellerInstagram:z.string().trim().max(300).optional().nullable(),sellerTelegram:z.string().trim().max(300).optional().nullable(),sellerFacebook:z.string().trim().max(300).optional().nullable(),sellerLinkedin:z.string().trim().max(300).optional().nullable(),sellerWebsite:z.string().trim().max(300).optional().nullable()});
const SETTINGS_SELECT={id:true,sellerShopName:true,sellerBio:true,sellerLogoUrl:true,sellerBannerUrl:true,sellerWhatsapp:true,sellerContactEmail:true,sellerContactPhone:true,sellerAddress:true,sellerCity:true,sellerCountry:true,sellerBankAccountNumber:true,sellerBankAccountName:true,sellerBankName:true,sellerAtomaPay:true,sellerInstagram:true,sellerTelegram:true,sellerFacebook:true,sellerLinkedin:true,sellerWebsite:true} as const;
const slugify=(v:string)=>v.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||`brand-${Date.now()}`;
async function syncSellerBrand(tx:Prisma.TransactionClient,userId:string){const s=await tx.user.findUnique({where:{id:userId},select:{id:true,fullName:true,sellerShopName:true,sellerBio:true,sellerLogoUrl:true,sellerBannerUrl:true,sellerWebsite:true,sellerCountry:true,sellerContactEmail:true,sellerContactPhone:true,sellerInstagram:true,sellerFacebook:true,sellerTelegram:true,sellerLinkedin:true}});if(!s)throw new Error('SELLER_NOT_FOUND');const name=s.sellerShopName?.trim()||s.fullName?.trim()||'برند فروشگاه';const existing=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`SELECT "id" FROM "SellerBrand" WHERE "sellerId"=${s.id} LIMIT 1`);if(existing[0]){await tx.$executeRaw(Prisma.sql`UPDATE "SellerBrand" SET "name"=${name},"description"=${s.sellerBio},"logoUrl"=${s.sellerLogoUrl},"bannerUrl"=${s.sellerBannerUrl},"website"=${s.sellerWebsite},"country"=${s.sellerCountry},"contactEmail"=${s.sellerContactEmail},"contactPhone"=${s.sellerContactPhone},"instagram"=${s.sellerInstagram},"facebook"=${s.sellerFacebook},"telegram"=${s.sellerTelegram},"linkedin"=${s.sellerLinkedin},"isActive"=true,"updatedAt"=CURRENT_TIMESTAMP WHERE "sellerId"=${s.id}`);return;}
const id=`brand_${s.id}`,brandSlug=`${slugify(name)}-${s.id.slice(0,8)}`;await tx.$executeRaw(Prisma.sql`INSERT INTO "SellerBrand" ("id","sellerId","name","slug","description","logoUrl","bannerUrl","website","country","contactEmail","contactPhone","instagram","facebook","telegram","linkedin","isActive","createdAt","updatedAt") VALUES (${id},${s.id},${name},${brandSlug},${s.sellerBio},${s.sellerLogoUrl},${s.sellerBannerUrl},${s.sellerWebsite},${s.sellerCountry},${s.sellerContactEmail},${s.sellerContactPhone},${s.sellerInstagram},${s.sellerFacebook},${s.sellerTelegram},${s.sellerLinkedin},true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("sellerId") DO UPDATE SET "name"=EXCLUDED."name","description"=EXCLUDED."description","logoUrl"=EXCLUDED."logoUrl","bannerUrl"=EXCLUDED."bannerUrl","isActive"=true,"updatedAt"=CURRENT_TIMESTAMP`);}
export async function OPTIONS(){return jsonPreflight();}
export async function GET(){const g=await requireSellerApi();if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});try{const row=await prisma.user.findUnique({where:{id:g.user.id},select:SETTINGS_SELECT});if(!row)return jsonError('not_found','Seller not found',{status:404});return jsonOk({...row,source:'db' as const});}catch(e){console.error('[seller/settings.GET]',e);return jsonError('query_failed','Unable to load seller settings',{status:500});}}
export async function PATCH(req:NextRequest){const g=await requireSellerApi();if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});let body:unknown;try{body=await req.json();}catch{return jsonError('invalid_json','Invalid JSON',{status:400});}const parsed=patchSchema.safeParse(body);if(!parsed.success)return jsonError('invalid_body','Invalid settings payload',{status:422,details:{issues:parsed.error.issues}});if(!Object.keys(parsed.data).length)return jsonError('empty_body','Nothing to update',{status:400});try{const result=await prisma.$transaction(async tx=>{const updated=await tx.user.update({where:{id:g.user.id},data:parsed.data,select:SETTINGS_SELECT});await syncSellerBrand(tx,g.user.id);return updated;});return jsonOk({...result,source:'db' as const});}catch(e){console.error('[seller/settings.PATCH]',e);const code=typeof e==='object'&&e&&'code'in e?String((e as {code?:unknown}).code):'';if(code==='P2002')return jsonError('duplicate','A unique seller value already exists.',{status:409});return jsonError('update_failed','Seller settings could not be saved.',{status:500});}}
export async function DELETE(){const g=await requireSellerApi();if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});try{await prisma.$transaction(async tx=>{await tx.user.update({where:{id:g.user.id},data:{isActive:false}});await tx.$executeRaw(Prisma.sql`UPDATE "SellerBrand" SET "isActive"=false,"updatedAt"=CURRENT_TIMESTAMP WHERE "sellerId"=${g.user.id}`);});return jsonOk({id:g.user.id,isActive:false});}catch(e){console.error('[seller/settings.DELETE]',e);return jsonError('delete_failed','Store could not be deactivated.',{status:500});}}
