import type { NextRequest } from 'next/server';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { prisma,isDatabaseConfigured } from '@/lib/db';
import { jsonError,jsonOk } from '@/lib/api/response';
import { requireAdminApi } from '@/lib/auth/require-admin-api';
import { listAllBanners } from '@/server/services/banner.service';
export const dynamic='force-dynamic';
const schema=z.object({id:z.string().optional(),key:z.string().trim().min(1).max(100),placement:z.string().trim().min(1).max(40),title:z.string().max(200).nullable().optional(),subtitle:z.string().max(500).nullable().optional(),ctaLabel:z.string().max(100).nullable().optional(),href:z.string().max(500).nullable().optional(),desktopImageUrl:z.string().url(),mobileImageUrl:z.string().url().nullable().optional(),startAt:z.string().datetime().nullable().optional(),endAt:z.string().datetime().nullable().optional(),sortOrder:z.number().int().min(0).max(10000).default(0),autoSlide:z.boolean().default(true),durationMs:z.number().int().min(1500).max(30000).default(5000),isActive:z.boolean().default(true)});
export async function GET(){const g=await requireAdminApi('banners.manage');if(!g.ok)return g.response;try{return jsonOk(await listAllBanners())}catch{return jsonError('query_failed','Failed to load banners',{status:500})}}
export async function POST(req:NextRequest){const g=await requireAdminApi('banners.manage');if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return jsonError('invalid_body','Invalid banner payload',{status:422,details:{issues:p.error.issues}});try{const d=p.data;const id=d.id??randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO "Banner" ("id","key","placement","title","subtitle","ctaLabel","href","desktopImageUrl","mobileImageUrl","startAt","endAt","sortOrder","autoSlide","durationMs","isActive","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,NOW(),NOW()) ON CONFLICT ("key") DO UPDATE SET "placement"=$3,"title"=$4,"subtitle"=$5,"ctaLabel"=$6,"href"=$7,"desktopImageUrl"=$8,"mobileImageUrl"=$9,"startAt"=$10,"endAt"=$11,"sortOrder"=$12,"autoSlide"=$13,"durationMs"=$14,"isActive"=$15,"updatedAt"=NOW()`,id,d.key,d.placement,d.title??null,d.subtitle??null,d.ctaLabel??null,d.href??null,d.desktopImageUrl,d.mobileImageUrl??null,d.startAt?new Date(d.startAt):null,d.endAt?new Date(d.endAt):null,d.sortOrder,d.autoSlide,d.durationMs,d.isActive);return jsonOk({id,key:d.key},{status:201})}catch{return jsonError('save_failed','Failed to save banner',{status:500})}}
export async function DELETE(req:NextRequest){const g=await requireAdminApi('banners.manage');if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});const id=new URL(req.url).searchParams.get('id');if(!id)return jsonError('invalid_id','Banner id is required',{status:400});try{await prisma.$executeRawUnsafe(`DELETE FROM "Banner" WHERE "id"=$1`,id);return jsonOk({deleted:true})}catch{return jsonError('delete_failed','Failed to delete banner',{status:500})}}
