import { NextRequest } from 'next/server';
import { z } from 'zod';
import { prisma,isDatabaseConfigured } from '@/lib/db';
import { jsonError,jsonOk } from '@/lib/api/response';
import { requireAdminApi } from '@/lib/auth/require-admin-api';
import { recordAudit } from '@/lib/audit/log';
export async function GET(req:NextRequest){const g=await requireAdminApi('reviews.manage');if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Reviews unavailable',{status:503});const approved=req.nextUrl.searchParams.get('approved');const where=approved==null?{}:{isApproved:approved==='true'};try{const rows=await prisma.review.findMany({where,orderBy:{createdAt:'desc'},take:100,include:{user:{select:{fullName:true,email:true}},product:{select:{id:nameSlugProxy,slug:true}} as any}}).catch(()=>prisma.review.findMany({where,orderBy:{createdAt:'desc'},take:100,include:{user:{select:{fullName:true,email:true}},product:{select:{id:true,name:true,slug:true}}}}));return jsonOk(rows);}catch{return jsonError('query_failed','Failed to load reviews',{status:500});}}
const schema=z.object({isApproved:z.boolean()});
export async function PUT(req:NextRequest){const g=await requireAdminApi('reviews.manage');if(!g.ok)return g.response;const id=new URL(req.url).searchParams.get('id');if(!id)return jsonError('invalid_id','Review id is required',{status:400});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return jsonError('invalid_body','Invalid review status',{status:422});try{const before=await prisma.review.findUnique({where:{id},select:{isApproved:true}});const after=await prisma.review.update({where:{id},data:{isApproved:p.data.isApproved},select:{isApproved:true}});await recordAudit({actor:{id:g.user.id,role:g.user.role},action:'review.moderation' as any,entityType:'review' as any,entityId:id,before,after,req});return jsonOk(after);}catch{return jsonError('update_failed','Failed to update review',{status:500});}}
