'use client';
import { useEffect, useState } from 'react';

interface Section { id: string; key: string; title?: string | null; subtitle?: string | null; type: string; configJson: Record<string, unknown>; sortOrder: number; isActive: boolean; }
export default function HomepageBuilderPage() {
  const [sections,setSections]=useState<Section[]>([]); const [status,setStatus]=useState('');
  const [draft,setDraft]=useState({key:'featured-products',title:'محصولات ویژه',subtitle:'انتخاب‌های برتر Eshop',type:'products',sortOrder:0,isActive:true,configJson:'{"limit":8}'});
  async function load(){ const r=await fetch('/api/admin/homepage'); const j=await r.json(); setSections(j.data??[]); }
  useEffect(()=>{void load();},[]);
  async function save(){ setStatus('در حال ذخیره…'); const r=await fetch('/api/admin/homepage',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...draft,configJson:JSON.parse(draft.configJson||'{}')})}); setStatus(r.ok?'ذخیره شد':'ذخیره ناموفق بود'); if(r.ok) await load(); }
  async function remove(id:string){ if(!confirm('این Section حذف شود؟')) return; await fetch(`/api/admin/homepage?id=${encodeURIComponent(id)}`,{method:'DELETE'}); await load(); }
  return <div className="space-y-6"><header><h1 className="text-2xl font-black">Homepage Builder</h1><p className="mt-1 text-sm text-muted-foreground">ترتیب و تنظیمات صفحه اصلی را بدون تغییر کد مدیریت کنید.</p></header><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-lg font-bold">Section جدید</h2><div className="mt-4 grid gap-3"><input className="rounded-xl border border-input bg-background px-3 py-2" placeholder="key" value={draft.key} onChange={e=>setDraft({...draft,key:e.target.value})}/><input className="rounded-xl border border-input bg-background px-3 py-2" placeholder="عنوان" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><input className="rounded-xl border border-input bg-background px-3 py-2" placeholder="زیرعنوان" value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})}/><div className="grid grid-cols-2 gap-3"><input className="rounded-xl border border-input bg-background px-3 py-2" placeholder="type" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}/><input type="number" className="rounded-xl border border-input bg-background px-3 py-2" value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})}/></div><textarea className="min-h-28 rounded-xl border border-input bg-background px-3 py-2 font-mono text-xs" value={draft.configJson} onChange={e=>setDraft({...draft,configJson:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/> فعال</label><button onClick={()=>void save()} className="rounded-xl bg-primary px-4 py-2.5 font-bold text-primary-foreground">ذخیره Section</button>{status&&<p className="text-xs text-muted-foreground">{status}</p>}</div></section><section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-lg font-bold">Sections فعلی</h2><div className="mt-4 space-y-2">{sections.map(s=><div key={s.id} className="flex items-center justify-between gap-3 rounded-xl border border-border p-3"><div><div className="font-semibold">{s.title||s.key}</div><div className="text-xs text-muted-foreground">{s.type} · ترتیب {s.sortOrder} · {s.isActive?'فعال':'غیرفعال'}</div></div><button onClick={()=>void remove(s.id)} className="text-xs font-bold text-red-500">حذف</button></div>)}{sections.length===0&&<p className="text-sm text-muted-foreground">هنوز Sectionای تعریف نشده است.</p>}</div></section></div></div>;
}
