import { Prisma, OrderStatus, PaymentMethod, PaymentStatus, Role, SellerStatus } from '@prisma/client';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import type { AdminStats, AdminOrderRow, AdminUserRow, AdminProductRow, AdminCategoryRow, SalesByDay, TopProduct, AdminSellerRow, AdminTransactionRow, AdminRevenueSummary } from './types';

export type DataSource = 'db' | 'empty' | 'unavailable';
export interface ListFilters { q?: string; page?: number; pageSize?: number; }
export interface OrderFilters extends ListFilters { status?: string; }
export interface Paged<T> { items: T[]; total: number; page: number; pageSize: number; source: DataSource; }
export interface SellerFilters extends ListFilters { status?: SellerStatus | 'all'; }
export interface TransactionFilters extends ListFilters { status?: string; method?: string; }
const pageArgs=(f:ListFilters)=>({page:Math.max(1,f.page??1),pageSize:Math.min(100,Math.max(1,f.pageSize??10))});
const unavailable=<T>(page=1,pageSize=10):Paged<T>=>({items:[],total:0,page,pageSize,source:'unavailable'});
const enumValue=<T extends string>(values:readonly T[],value:string|undefined):T|undefined=>value&&values.includes(value as T)?value as T:undefined;
const ORDER_STATUSES=Object.values(OrderStatus) as readonly OrderStatus[];
const PAYMENT_METHODS=Object.values(PaymentMethod) as readonly PaymentMethod[];
const PAYMENT_STATUSES=Object.values(PaymentStatus) as readonly PaymentStatus[];

export async function getAdminStats():Promise<AdminStats&{source:DataSource}>{
 if(!isDatabaseConfigured())return{users:0,products:0,orders:0,categories:0,revenue:0,currency:'AFN',source:'unavailable'};
 try{const [users,products,orders,categories,agg]=await Promise.all([prisma.user.count(),prisma.product.count(),prisma.order.count(),prisma.category.count(),prisma.order.aggregate({_sum:{total:true}})]);return{users,products,orders,categories,revenue:agg._sum.total?.toNumber()??0,currency:'AFN',source:users===0&&products===0&&orders===0&&categories===0?'empty':'db'};}catch(err){console.error('[admin/stats] DB error:',err);return{users:0,products:0,orders:0,categories:0,revenue:0,currency:'AFN',source:'unavailable'};}}

export async function listAdminProducts(f:ListFilters={}):Promise<Paged<AdminProductRow>>{const{page,pageSize}=pageArgs(f);const q=f.q?.trim()??'';if(!isDatabaseConfigured())return unavailable(page,pageSize);try{const where:Prisma.ProductWhereInput=q?{OR:[{name:{contains:q,mode:'insensitive'}},{slug:{contains:q,mode:'insensitive'}},{region:{contains:q,mode:'insensitive'}}]}:{};const[rows,total]=await Promise.all([prisma.product.findMany({where,include:{category:true},orderBy:{createdAt:'desc'},take:pageSize,skip:(page-1)*pageSize}),prisma.product.count({where})]);return{items:rows.map(p=>({id:p.id,slug:p.slug,name:p.name,price:p.price.toNumber(),currency:p.currency,categoryName:p.category.name,region:p.region,inStock:p.inStock,isHero:p.badge==='hero',createdAt:p.createdAt.toISOString()})),total,page,pageSize,source:total===0?'empty':'db'};}catch(err){console.error('[admin/products] DB error:',err);return unavailable(page,pageSize);}}

export async function listAdminCategories():Promise<{items:AdminCategoryRow[];source:DataSource}>{if(!isDatabaseConfigured())return{items:[],source:'unavailable'};try{const rows=await prisma.category.findMany({include:{_count:{select:{products:true}}},orderBy:{name:'asc'}});return{items:rows.map(c=>({id:c.id,key:c.key,name:c.name,slug:c.slug,productCount:c._count.products})),source:rows.length?'db':'empty'};}catch(err){console.error('[admin/categories] DB error:',err);return{items:[],source:'unavailable'};}}

export async function listAdminOrders(f:OrderFilters={}):Promise<Paged<AdminOrderRow>>{const{page,pageSize}=pageArgs(f);const q=f.q?.trim()??'';const status=enumValue(ORDER_STATUSES,f.status);if(!isDatabaseConfigured())return unavailable(page,pageSize);try{const where:Prisma.OrderWhereInput={...(status?{status}:{}),...(q?{OR:[{reference:{contains:q,mode:'insensitive'}},{address:{fullName:{contains:q,mode:'insensitive'}}}]}:{})};const[rows,total]=await Promise.all([prisma.order.findMany({where,include:{address:true},orderBy:{createdAt:'desc'},take:pageSize,skip:(page-1)*pageSize}),prisma.order.count({where})]);return{items:rows.map(o=>({id:o.id,reference:o.reference,status:o.status,paymentMethod:o.paymentMethod,total:o.total.toNumber(),currency:o.currency,itemCount:o.itemCount,customerName:o.address.fullName,createdAt:o.createdAt.toISOString()})),total,page,pageSize,source:total?'db':'empty'};}catch(err){console.error('[admin/orders] DB error:',err);return unavailable(page,pageSize);}}

export async function listAdminUsers(f:ListFilters={}):Promise<Paged<AdminUserRow>>{const{page,pageSize}=pageArgs(f);const q=f.q?.trim()??'';if(!isDatabaseConfigured())return unavailable(page,pageSize);try{const where:Prisma.UserWhereInput=q?{OR:[{fullName:{contains:q,mode:'insensitive'}},{email:{contains:q,mode:'insensitive'}},{phone:{contains:q}}]}:{};const[rows,total]=await Promise.all([prisma.user.findMany({where,orderBy:{createdAt:'desc'},take:pageSize,skip:(page-1)*pageSize,include:{_count:{select:{orders:true}}}}),prisma.user.count({where})]);return{items:rows.map(u=>({id:u.id,fullName:u.fullName,email:u.email,phone:u.phone,role:u.role,isActive:u.isActive,createdAt:u.createdAt.toISOString(),orderCount:u._count.orders})),total,page,pageSize,source:total?'db':'empty'};}catch(err){console.error('[admin/users] DB error:',err);return unavailable(page,pageSize);}}

export async function getSalesByDay(days=14):Promise<{items:SalesByDay[];source:DataSource}>{days=Math.min(90,Math.max(1,days));if(!isDatabaseConfigured())return{items:[],source:'unavailable'};try{const since=new Date(Date.now()-days*86400000);const rows=await prisma.order.findMany({where:{createdAt:{gte:since}},select:{createdAt:true,total:true}});const buckets=new Map<string,{count:number;revenue:number}>();for(let i=0;i<days;i++)buckets.set(new Date(Date.now()-(days-1-i)*86400000).toISOString().slice(0,10),{count:0,revenue:0});for(const r of rows){const b=buckets.get(r.createdAt.toISOString().slice(0,10));if(b){b.count++;b.revenue+=r.total.toNumber();}}return{items:Array.from(buckets.entries()).map(([date,v])=>({date,...v})),source:rows.length?'db':'empty'};}catch(err){console.error('[admin/sales-by-day] DB error:',err);return{items:[],source:'unavailable'};}}

export async function getTopProducts(limit=5):Promise<{items:TopProduct[];source:DataSource}>{limit=Math.min(50,Math.max(1,limit));if(!isDatabaseConfigured())return{items:[],source:'unavailable'};try{const grouped=await prisma.orderItem.groupBy({by:['slug','name'],_sum:{quantity:true,price:true},orderBy:{_sum:{quantity:'desc'}},take:limit});return{items:grouped.map(g=>({slug:g.slug,name:g.name,units:g._sum.quantity??0,revenue:g._sum.price?.toNumber()??0})),source:grouped.length?'db':'empty'};}catch(err){console.error('[admin/top-products] DB error:',err);return{items:[],source:'unavailable'};}}

export async function listAdminSellers(f:SellerFilters={}):Promise<Paged<AdminSellerRow>>{const{page,pageSize}=pageArgs(f);const q=f.q?.trim()??'';const status=f.status&&f.status!=='all'?f.status:undefined;if(!isDatabaseConfigured())return unavailable(page,pageSize);try{const where:Prisma.UserWhereInput={AND:[{OR:[{role:Role.seller},{sellerStatus:{not:SellerStatus.none}}]},...(status?[{sellerStatus:status}]:[]),...(q?[{OR:[{fullName:{contains:q,mode:'insensitive'}},{email:{contains:q,mode:'insensitive'}},{sellerShopName:{contains:q,mode:'insensitive'}}]}]:[])]};const[rows,total]=await Promise.all([prisma.user.findMany({where,orderBy:{createdAt:'desc'},take:pageSize,skip:(page-1)*pageSize,include:{_count:{select:{products:true}}}}),prisma.user.count({where})]);return{items:rows.map(u=>({id:u.id,fullName:u.fullName,email:u.email,phone:u.phone,shopName:u.sellerShopName,bio:u.sellerBio,sellerStatus:u.sellerStatus,isActive:u.isActive,productCount:u._count.products,createdAt:u.createdAt.toISOString()})),total,page,pageSize,source:total?'db':'empty'};}catch(err){console.error('[admin/sellers] DB error:',err);return unavailable(page,pageSize);}}

export async function getAdminSeller(id:string):Promise<AdminSellerRow|null>{if(!isDatabaseConfigured())return null;try{const u=await prisma.user.findUnique({where:{id},include:{_count:{select:{products:true}}}});if(!u)return null;return{id:u.id,fullName:u.fullName,email:u.email,phone:u.phone,shopName:u.sellerShopName,bio:u.sellerBio,sellerStatus:u.sellerStatus,isActive:u.isActive,productCount:u._count.products,createdAt:u.createdAt.toISOString()};}catch(err){console.error('[admin/seller] DB error:',err);return null;}}

export async function listAdminTransactions(f:TransactionFilters={}):Promise<Paged<AdminTransactionRow>>{const{page,pageSize}=pageArgs(f);const q=f.q?.trim()??'';const status=enumValue(PAYMENT_STATUSES,f.status);const method=enumValue(PAYMENT_METHODS,f.method);if(!isDatabaseConfigured())return unavailable(page,pageSize);try{const where:Prisma.TransactionWhereInput={...(status?{status}:{}),...(method?{method}:{}),...(q?{OR:[{reference:{contains:q,mode:'insensitive'}},{order:{reference:{contains:q,mode:'insensitive'}}}]}:{})};const[rows,total]=await Promise.all([prisma.transaction.findMany({where,include:{order:{select:{reference:true}}},orderBy:{createdAt:'desc'},take:pageSize,skip:(page-1)*pageSize}),prisma.transaction.count({where})]);return{items:rows.map(t=>({id:t.id,reference:t.reference,orderId:t.orderId,orderReference:t.order.reference,provider:t.provider,method:t.method,status:t.status,amount:t.amount.toNumber(),currency:t.currency,paidAt:t.paidAt?.toISOString()??null,createdAt:t.createdAt.toISOString()})),total,page,pageSize,source:total?'db':'empty'};}catch(err){console.error('[admin/transactions] DB error:',err);return unavailable(page,pageSize);}}

export async function getAdminRevenue(days=30):Promise<AdminRevenueSummary&{source:DataSource}>{days=Math.min(90,Math.max(1,days));if(!isDatabaseConfigured())return{gross:0,paid:0,pending:0,refunded:0,currency:'AFN',orderCount:0,paidOrderCount:0,averageOrderValue:0,byDay:[],byMethod:[],source:'unavailable'};try{const since=new Date(Date.now()-days*86400000);const[orders,txns]=await Promise.all([prisma.order.findMany({where:{createdAt:{gte:since}},select:{createdAt:true,total:true,paymentStatus:true}}),prisma.transaction.findMany({where:{createdAt:{gte:since}},select:{amount:true,status:true,method:true}})]);const gross=orders.reduce((s,o)=>s+o.total.toNumber(),0);const paid=orders.filter(o=>o.paymentStatus===PaymentStatus.paid).reduce((s,o)=>s+o.total.toNumber(),0);const pending=orders.filter(o=>o.paymentStatus===PaymentStatus.pending).reduce((s,o)=>s+o.total.toNumber(),0);const refunded=txns.filter(t=>t.status===PaymentStatus.refunded).reduce((s,t)=>s+t.amount.toNumber(),0);const paidOrderCount=orders.filter(o=>o.paymentStatus===PaymentStatus.paid).length;const buckets=new Map<string,{count:number;revenue:number}>();for(let i=0;i<days;i++)buckets.set(new Date(Date.now()-(days-1-i)*86400000).toISOString().slice(0,10),{count:0,revenue:0});for(const o of orders){const b=buckets.get(o.createdAt.toISOString().slice(0,10));if(b){b.count++;b.revenue+=o.total.toNumber();}}const methodMap=new Map<string,{amount:number;count:number}>();for(const t of txns.filter(x=>x.status===PaymentStatus.paid)){const m=methodMap.get(t.method)??{amount:0,count:0};m.amount+=t.amount.toNumber();m.count++;methodMap.set(t.method,m);}return{gross,paid,pending,refunded,currency:'AFN',orderCount:orders.length,paidOrderCount,averageOrderValue:paidOrderCount?Math.round(paid/paidOrderCount):0,byDay:Array.from(buckets.entries()).map(([date,v])=>({date,...v})),byMethod:Array.from(methodMap.entries()).map(([method,v])=>({method,...v})),source:orders.length||txns.length?'db':'empty'};}catch(err){console.error('[admin/revenue] DB error:',err);return{gross:0,paid:0,pending:0,refunded:0,currency:'AFN',orderCount:0,paidOrderCount:0,averageOrderValue:0,byDay:[],byMethod:[],source:'unavailable'};}}
