import type { NextRequest } from 'next/server';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import { jsonError, jsonOk, jsonPreflight } from '@/lib/api/response';
import { requireSellerApi } from '@/lib/auth/require-seller-api';
export const dynamic='force-dynamic';
const INTERNAL_MEDIA_PATH=/^\/api\/media\/[A-Za-z0-9_-]{8,80}$/;const optionalText=(max:number)=>z.string().trim().max(max).optional().nullable();const optionalHttpUrl=(max:number)=>optionalText(max).refine(v=>{if(v==null||v==='')return true;try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}},'نشانی اینترنتی نامعتبر است');const optionalMediaUrl=(max:number)=>optionalText(max).refine(v=>{if(v==null||v===''||INTERNAL_MEDIA_PATH.test(v))return true;try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}},'نشانی تصویر نامعتبر است');const optionalJson=optionalText(4000).refine(v=>{if(v==null||v==='')return true;try{JSON.parse(v);return true}catch{return false}},'مشخصات برند نامعتبر است');
const brandSchema=z.object({name:z.string().trim().min(2,'نام برند حداقل ۲ حرف باشد').max(120).optional(),slug:z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).optional(),description:optionalText(1500),logoUrl:optionalMediaUrl(500),bannerUrl:optionalMediaUrl(500),website:optionalHttpUrl(300),country:optionalText(120),contactEmail:z.string().trim().email('ایمیل نامعتبر است').max(200).optional().nullable(),contactPhone:optionalText(40),instagram:optionalHttpUrl(300),facebook:optionalHttpUrl(300),telegram:optionalHttpUrl(300),linkedin:optionalHttpUrl(300),attributesJson:optionalJson,isActive:z.boolean().optional()}).strict().refine(v=>Object.keys(v).length>0,{message:'حداقل یک بخش از اطلاعات برند لازم است'});
const slugify=(v:string)=>{const s=v.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);return s||`brand-${Date.now()}`};
async function ensureSellerBrand(sellerId:string){const existing=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`SELECT * FROM "SellerBrand" WHERE "sellerId"=${sellerId} LIMIT 1`);if(existing[0])return existing[0];const seller=await prisma.user.findUnique({where:{id:sellerId},select:{fullName:true,sellerShopName:true,sellerBio:true,sellerLogoUrl:true,sellerBannerUrl:true,sellerWebsite:true,sellerCountry:true,sellerContactEmail:true,sellerContactPhone:true,sellerInstagram:true,sellerFacebook:true,sellerTelegram:true,sellerLinkedin:true}});if(!seller)return null;const name=seller.sellerShopName?.trim()||seller.fullName,id=`brand_${sellerId}`,slug=`${slugify(name)}-${sellerId.slice(0,8)}`;const rows=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`INSERT INTO "SellerBrand" ("id","sellerId","name","slug","description","logoUrl","bannerUrl","website","country","contactEmail","contactPhone","instagram","facebook","telegram","linkedin") VALUES (${id},${sellerId},${name},${slug},${seller.sellerBio},${seller.sellerLogoUrl},${seller.sellerBannerUrl},${seller.sellerWebsite},${seller.sellerCountry},${seller.sellerContactEmail},${seller.sellerContactPhone},${seller.sellerInstagram},${seller.sellerFacebook},${seller.sellerTelegram},${seller.sellerLinkedin}) ON CONFLICT ("sellerId") DO UPDATE SET "updatedAt"=CURRENT_TIMESTAMP RETURNING *`);return rows[0]??null}
export async function OPTIONS(){return jsonPreflight()}
export async function GET(){const g=await requireSellerApi();if(!g.ok)return g.response;if(g.user.role==='admin')return jsonError('forbidden','دسترسی فروشنده لازم است',{status:403});if(!isDatabaseConfigured())return jsonError('db_unavailable','پایگاه داده در دسترس نیست',{status:503});try{const brand=await ensureSellerBrand(g.user.id);if(!brand)return jsonError('not_found','فروشنده پیدا نشد',{status:404});return jsonOk(brand)}catch(err){console.error('[seller/brand.GET]',err);return jsonError('query_failed','بارگذاری برند ناموفق بود',{status:500})}}
export async function PATCH(req:NextRequest){const g=await requireSellerApi();if(!g.ok)return g.response;if(g.user.role==='admin')return jsonError('forbidden','دسترسی فروشنده لازم است',{status:403});if(!isDatabaseConfigured())return jsonError('db_unavailable','پایگاه داده در دسترس نیست',{status:503});let body:unknown;try{body=await req.json()}catch{return jsonError('invalid_json','درخواست نامعتبر است',{status:400})}const parsed=brandSchema.safeParse(body);if(!parsed.success)return jsonError('invalid_body',parsed.error.issues[0]?.message??'اطلاعات برند نامعتبر است',{status:422,details:{issues:parsed.error.issues}});try{const current=await ensureSellerBrand(g.user.id);if(!current)return jsonError('not_found','فروشنده پیدا نشد',{status:404});const d=parsed.data,parts:Prisma.Sql[]=[Prisma.sql`"updatedAt"=CURRENT_TIMESTAMP`];if(d.name!==undefined)parts.push(Prisma.sql`"name"=${d.name}`);if(d.slug!==undefined)parts.push(Prisma.sql`"slug"=${d.slug}`);for(const[column,value]of[['description',d.description],['logoUrl',d.logoUrl],['bannerUrl',d.bannerUrl],['website',d.website],['country',d.country],['contactEmail',d.contactEmail],['contactPhone',d.contactPhone],['instagram',d.instagram],['facebook',d.facebook],['telegram',d.telegram],['linkedin',d.linkedin]]as const)if(value!==undefined)parts.push(Prisma.sql`${Prisma.raw(`"${column}"`)}=${value}`);if(d.attributesJson!==undefined)parts.push(d.attributesJson==null||d.attributesJson===''?Prisma.sql`"attributesJson"=NULL`:Prisma.sql`"attributesJson"=${d.attributesJson}::jsonb`);if(d.isActive!==undefined)parts.push(Prisma.sql`"isActive"=${d.isActive}`);const rows=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`UPDATE "SellerBrand" SET ${Prisma.join(parts,', ')} WHERE "sellerId"=${g.user.id} RETURNING *`);if(!rows[0])return jsonError('update_failed','ذخیره برند ناموفق بود',{status:500});return jsonOk(rows[0])}catch(err:unknown){const code=typeof err==='object'&&err&&'code'in err?String((err as {code?:unknown}).code):'';if(code==='23505'||code==='P2002')return jsonError('duplicate_slug','این شناسهٔ برند قبلاً استفاده شده است',{status:409});console.error('[seller/brand.PATCH]',err);return jsonError('update_failed','ذخیره برند ناموفق بود',{status:500})}}
