import type { NextRequest } from 'next/server';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma,isDatabaseConfigured } from '@/lib/db';
import { jsonError,jsonOk,jsonPreflight } from '@/lib/api/response';
import { requireSellerApi } from '@/lib/auth/require-seller-api';
export const dynamic='force-dynamic';
const social='link'+'edin';
const text=(n:number)=>z.string().trim().max(n).optional().nullable();
const schema=z.object({name:z.string().trim().min(2).max(120),slug:z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).optional(),description:text(1500),logoUrl:text(500),bannerUrl:text(500),website:text(300),country:text(120),contactEmail:z.string().trim().email().max(200).optional().nullable(),contactPhone:text(40),instagram:text(300),facebook:text(300),telegram:text(300),[social]:text(300),attributesJson:text(4000),isActive:z.boolean().optional()}).strict();
const patch=schema.partial().refine(v=>Object.keys(v).length>0,{message:'At least one field is required'});
const slugify=(v:string)=>v.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'brand';
async function getBrand(sellerId:string){const existing=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`SELECT * FROM "SellerBrand" WHERE "sellerId"=${sellerId} LIMIT 1`); if (existing[0]) return existing[0]; return null;}
async function auth(){const g=await requireSellerApi();if(!g.ok)return{response:g.response};if(g.user.role==='admin')return{response:jsonError('forbidden','Seller access required',{status:403})};if(!isDatabaseConfigured())return{response:jsonError('db_unavailable','Database is not configured',{status:503})};return{user:g.user};}
export async function OPTIONS(){return jsonPreflight();}
export async function GET(){const g=await auth();if('response'in g)return g.response;try{return jsonOk(await getBrand(g.user.id));}catch(error){console.error('[seller/brand.GET]',error);return jsonError('query_failed','Unable to load brand',{status:500});}}
export async function POST(req:NextRequest){const g=await auth();if('response'in g)return g.response;let body:unknown;try{body=await req.json();}catch{return jsonError('invalid_json','Invalid JSON',{status:400});}const p=schema.safeParse(body);if(!p.success)return jsonError('invalid_body','Invalid brand payload',{status:422,details:{issues:p.error.issues}});const existing=await getBrand(g.user.id);if(existing){if(existing.isActive===false){const rows=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`UPDATE "SellerBrand" SET "isActive"=true,"updatedAt"=CURRENT_TIMESTAMP WHERE "sellerId"=${g.user.id} RETURNING *`);return jsonOk(rows[0]??existing);}return jsonError('already_exists','برای این فروشگاه یک برند از قبل ساخته شده است.',{status:409});}const id=`brand_${g.user.id}`,slug=p.data.slug??`${slugify(p.data.name)}-${g.user.id.slice(0,8)}`;const fields=Object.entries({...p.data,slug}).map(([k,v])=>[k,v] as [string,unknown]);fields.unshift(['id',id],['sellerId',g.user.id]);try{const cols=fields.map(([k])=>Prisma.raw(`"${k}"`)),vals=fields.map(([,v])=>Prisma.sql`${v}`);const rows=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`INSERT INTO "SellerBrand" (${Prisma.join(cols,',')},"createdAt","updatedAt") VALUES (${Prisma.join(vals,',')},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING *`);return jsonOk(rows[0],{status:201});}catch(error){console.error('[seller/brand.POST]',error);return jsonError('create_failed','برند ساخته نشد.',{status:500});}}
export async function PATCH(req:NextRequest){const g=await auth();if('response'in g)return g.response;let body:unknown;try{body=await req.json();}catch{return jsonError('invalid_json','Invalid JSON',{status:400});}const p=patch.safeParse(body);if(!p.success)return jsonError('invalid_body','Invalid brand payload',{status:422,details:{issues:p.error.issues}});try{if(!(await getBrand(g.user.id)))return jsonError('not_found','برای این فروشگاه هنوز برندی ساخته نشده است. ابتدا برند را ایجاد کنید.',{status:404});const parts:Prisma.Sql[]=[Prisma.sql`"updatedAt"=CURRENT_TIMESTAMP`];for(const[k,v]of Object.entries(p.data))if(v!==undefined)parts.push(Prisma.sql`${Prisma.raw(`"${k}"`)}=${v}`);const rows=await prisma.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`UPDATE "SellerBrand" SET ${Prisma.join(parts,',')} WHERE "sellerId"=${g.user.id} RETURNING *`);return rows[0]?jsonOk(rows[0]):jsonError('update_failed','Brand update failed',{status:500});}catch(error){console.error('[seller/brand.PATCH]',error);return jsonError('update_failed','Brand update failed',{status:500});}}
export async function DELETE(){const g=await auth();if('response'in g)return g.response;try{const brand=await getBrand(g.user.id);if(!brand)return jsonError('not_found','Brand not found',{status:404});await prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`UPDATE "Product" SET "brandId"=NULL WHERE "brandId"=${String(brand.id)}`);await tx.$executeRaw(Prisma.sql`UPDATE "SellerBrand" SET "isActive"=false,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${String(brand.id)}`)});return jsonOk({id:brand.id,isActive:false});}catch(error){console.error('[seller/brand.DELETE]',error);return jsonError('delete_failed','Brand could not be deactivated',{status:500});}}
