import Link from 'next/link';
import { getTranslations } from 'next-intl/server';
import { DollarSign, TrendingUp, RefreshCcw, Clock } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { StatCard } from '@/features/admin/components/stat-card';
import { BarChart } from '@/features/admin/components/bar-chart';
import { getAdminRevenue } from '@/features/admin/lib/queries';
import { formatMoney } from '@/features/admin/lib/format';

export const dynamic = 'force-dynamic';
interface Props { params: Promise<{ locale: string }>; searchParams: Promise<{ days?: string }> }

export default async function AdminRevenueReportPage({ params, searchParams }: Props) {
  const { locale } = await params; const sp = await searchParams; const t = await getTranslations('admin.reportsPage');
  const days = Math.min(180, Math.max(7, parseInt(sp.days ?? '30', 10) || 30)); const data = await getAdminRevenue(days); const unavailable = data.source === 'unavailable';
  const ranges = [7, 30, 90, 180];
  const methodLabel = (method: string) => ({ cod: t('cash'), bank_transfer: t('bank'), whatsapp: t('whatsapp'), atoma_pay: t('atoma') })[method] ?? method;
  return <div className="space-y-6"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-display text-2xl font-black text-foreground">{t('title')}</h2><p className="mt-1 text-sm text-muted-foreground">{t('subtitle', { days, amount: formatMoney(data.gross, data.currency) })}</p>{unavailable && <p role="alert" className="mt-2 text-sm font-semibold text-destructive">Database unavailable. Report data could not be loaded.</p>}</div><div className="flex flex-wrap gap-2 rounded-xl border border-border bg-card p-1" aria-label="بازه گزارش">{ranges.map((value) => <Link key={value} href={`/${locale}/admin/reports?days=${value}`} className={`rounded-lg px-3 py-2 text-xs font-bold transition-colors ${days === value ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-muted'}`}>{value} روز</Link>)}</div></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label={t('gross')} value={formatMoney(data.gross, data.currency)} icon={<DollarSign className="h-5 w-5" />} tone="success" /><StatCard label={t('paid')} value={formatMoney(data.paid, data.currency)} icon={<TrendingUp className="h-5 w-5" />} tone="info" /><StatCard label={t('pending')} value={formatMoney(data.pending, data.currency)} icon={<Clock className="h-5 w-5" />} tone="warning" /><StatCard label={t('refunded')} value={formatMoney(data.refunded, data.currency)} icon={<RefreshCcw className="h-5 w-5" />} tone="default" /></section><section className="grid gap-4 lg:grid-cols-3"><Card className="p-5 lg:col-span-2"><div className="mb-4"><h3 className="text-base font-semibold text-foreground">{t('daily', { days })}</h3><p className="text-xs text-muted-foreground">{t('ordersSummary', { orders: data.orderCount.toLocaleString(), paidOrders: data.paidOrderCount.toLocaleString(), average: formatMoney(data.averageOrderValue, data.currency) })}</p></div><BarChart data={data.byDay.map((d) => ({ label: d.date, value: d.revenue }))} formatValue={(v) => formatMoney(v, data.currency)} ariaLabel={t('daily', { days })} /></Card><Card className="p-5"><h3 className="mb-4 text-base font-semibold text-foreground">{t('methods')}</h3>{data.byMethod.length === 0 ? <p className="text-sm text-muted-foreground">{t('noData')}</p> : <ul className="space-y-3">{data.byMethod.map((m) => { const pct = data.paid > 0 ? Math.round((m.amount / data.paid) * 100) : 0; return <li key={m.method} className="space-y-1"><div className="flex items-center justify-between text-sm"><span>{methodLabel(m.method)}</span><span className="font-semibold">{formatMoney(m.amount, data.currency)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${pct}%` }} aria-hidden="true" /></div><div className="flex justify-between text-xs text-muted-foreground"><span>{m.count.toLocaleString()} {t('transactions')}</span><span>{pct}%</span></div></li>; })}</ul>}</Card></section></div>;
}