import { NextRequest, NextResponse } from 'next/server';
import { jsonError, jsonOk } from '@/lib/api/response';
import { requireAdminApi } from '@/lib/auth/require-admin-api';
import { createMediaAsset, deleteMediaAsset, listMediaAssets } from '@/features/admin/lib/control-store';
import { uploadPersistent, deletePersistent } from '@/lib/storage';

export const dynamic='force-dynamic';
const images=new Set(['image/jpeg','image/png','image/webp','image/gif']); const videos=new Set(['video/mp4','video/webm','video/ogg']);
export async function GET(req:NextRequest){const guard=await requireAdminApi('media.manage');if(!guard.ok)return guard.response;try{return jsonOk(await listMediaAssets({q:req.nextUrl.searchParams.get('q')??undefined,kind:req.nextUrl.searchParams.get('kind')??undefined,page:Number(req.nextUrl.searchParams.get('page')??1),pageSize:Number(req.nextUrl.searchParams.get('pageSize')??30)}));}catch{return jsonError('db_unavailable','Media library is unavailable',{status:503});}}
export async function POST(req:NextRequest){const guard=await requireAdminApi('media.manage');if(!guard.ok)return guard.response;try{const fd=await req.formData();const file=fd.get('file');if(!(file instanceof File))return jsonError('missing_file','File is required',{status:400});const kind=images.has(file.type)?'image':videos.has(file.type)?'video':null;if(!kind)return jsonError('invalid_type','Unsupported media type',{status:400});const max=kind==='video'?100:10;if(file.size>max*1024*1024)return jsonError('file_too_large',`Maximum size is ${max} MB`,{status:400});const uploaded=await uploadPersistent(file,`admin/${kind}s`);const id=await createMediaAsset({url:uploaded.secure_url,kind,mimeType:file.type,fileName:file.name,sizeBytes:file.size,folder:`admin/${kind}s`,createdById:guard.user.id});return jsonOk({id,url:uploaded.secure_url,kind,mimeType:file.type,fileName:file.name,sizeBytes:file.size},{status:201});}catch{return jsonError('upload_failed','Media upload failed',{status:500});}}
export async function DELETE(req:NextRequest){const guard=await requireAdminApi('media.manage');if(!guard.ok)return guard.response;const id=req.nextUrl.searchParams.get('id');const url=req.nextUrl.searchParams.get('url');if(!id)return jsonError('invalid_id','Media id is required',{status:400});try{if(url)await deletePersistent(url);await deleteMediaAsset(id);return jsonOk({deleted:true});}catch{return jsonError('delete_failed','Media deletion failed',{status:500});}}
