import type { NextRequest } from 'next/server';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import { jsonError, jsonOk } from '@/lib/api/response';
import { requireAdminApi } from '@/lib/auth/require-admin-api';
import { createMediaAsset, deleteMediaAsset, listMediaAssets } from '@/features/admin/lib/control-store';
import { isInternalMediaUrl } from '@/features/admin/lib/media-url';
import { uploadPersistent, deletePersistent } from '@/lib/storage';
import { hasValidImageSignature, imageUploadError } from '@/lib/media/image-upload';
export const dynamic='force-dynamic';
async function mediaUsage(url:string){if(!isDatabaseConfigured())return null;const p=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "Product" WHERE CAST("imagesJson" AS text) LIKE ${`%${url}%`} LIMIT 1`;if(p[0])return'product';const c=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "CategoryMeta" WHERE "imageUrl"=${url} LIMIT 1`;if(c[0])return'category';const b=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "Banner" WHERE "desktopImageUrl"=${url} OR "mobileImageUrl"=${url} LIMIT 1`;if(b[0])return'banner';const h=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "HomepageSection" WHERE CAST("configJson" AS text) LIKE ${`%${url}%`} LIMIT 1`;if(h[0])return'homepage';return null}
function positiveInt(value:string|null,fallback:number,max?:number){const parsed=Number.parseInt(value??'',10);if(!Number.isFinite(parsed)||parsed<1)return fallback;return max===undefined?parsed:Math.min(max,parsed)}
export async function GET(req:NextRequest){const g=await requireAdminApi('media.manage');if(!g.ok)return g.response;try{const page=positiveInt(req.nextUrl.searchParams.get('page'),1),pageSize=Math.max(10,positiveInt(req.nextUrl.searchParams.get('pageSize'),30,100));return jsonOk(await listMediaAssets({q:req.nextUrl.searchParams.get('q')??undefined,kind:req.nextUrl.searchParams.get('kind')??undefined,page,pageSize}))}catch{return jsonError('db_unavailable','کتابخانه رسانه موقتاً در دسترس نیست.',{status:503})}}
export async function POST(req:NextRequest){const g=await requireAdminApi('media.manage');if(!g.ok)return g.response;let uploadedUrl:string|null=null;try{const fd=await req.formData(),file=fd.get('file');if(!(file instanceof File))return jsonError('missing_file','فایلی ارسال نشده است.',{status:400});const validationError=imageUploadError(file);if(validationError)return jsonError('invalid_type',validationError,{status:415});const header=Buffer.from(await file.slice(0,4096).arrayBuffer());if(!hasValidImageSignature(header,file.type))return jsonError('invalid_signature','محتوای فایل با نوع تصویر اعلام‌شده مطابقت ندارد.',{status:400});const uploaded=await uploadPersistent(file,'admin/images'),secureUrl=uploaded.secure_url??null;if(!secureUrl)return jsonError('storage_no_url','فضای ذخیره‌سازی آدرس تصویر را برنگرداند.',{status:502});uploadedUrl=secureUrl;const publicId=uploaded.public_id??null,dbFallback=publicId?.startsWith('db/')===true,id=dbFallback&&publicId?publicId.slice(3):await createMediaAsset({url:secureUrl,kind:'image',mimeType:file.type,fileName:file.name,sizeBytes:file.size,folder:'admin/images',createdById:g.user.id});if(dbFallback&&isDatabaseConfigured())await prisma.$executeRaw`UPDATE "MediaAsset" SET "createdById"=${g.user.id} WHERE "id"=${id}`;return jsonOk({id,url:secureUrl,kind:'image',mimeType:file.type,fileName:file.name,sizeBytes:file.size},{status:201})}catch{if(uploadedUrl){try{await deletePersistent(uploadedUrl)}catch{}}return jsonError('upload_failed','آپلود تصویر ناموفق بود.',{status:500})}}
export async function DELETE(req:NextRequest){const g=await requireAdminApi('media.manage');if(!g.ok)return g.response;const id=req.nextUrl.searchParams.get('id');if(!id)return jsonError('invalid_id','شناسه رسانه لازم است.',{status:400});try{const rows=await prisma.$queryRaw<Array<{id:string;url:string}>>`SELECT "id","url" FROM "MediaAsset" WHERE "id"=${id} LIMIT 1`;const asset=rows[0];if(!asset)return jsonError('not_found','رسانه پیدا نشد.',{status:404});const usage=await mediaUsage(asset.url);if(usage)return jsonError('media_in_use','این تصویر هنوز در سایت استفاده می‌شود و قابل حذف نیست.',{status:409});await deletePersistent(asset.url);if(!isInternalMediaUrl(asset.url))await deleteMediaAsset(id);return jsonOk({deleted:true})}catch{return jsonError('delete_failed','حذف تصویر ناموفق بود.',{status:500})}}
