import type { NextRequest } from 'next/server';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import { jsonError, jsonOk } from '@/lib/api/response';
import { requireAdminApi } from '@/lib/auth/require-admin-api';
import { createMediaAsset, deleteMediaAsset, listMediaAssets } from '@/features/admin/lib/control-store';
import { isInternalMediaUrl } from '@/features/admin/lib/media-url';
import { uploadPersistent, deletePersistent, isPersistentStorageConfigured } from '@/lib/storage';
export const dynamic='force-dynamic';
const IMAGE_TYPES=new Set(['image/jpeg','image/png','image/webp','image/gif']);const VIDEO_TYPES=new Set(['video/mp4','video/webm','video/ogg']);
const IMAGE_EXTENSIONS:Record<string,string[]|undefined>={'image/jpeg':['jpg','jpeg'],'image/png':['png'],'image/webp':['webp'],'image/gif':['gif']};const VIDEO_EXTENSIONS:Record<string,string[]|undefined>={'video/mp4':['mp4','m4v'],'video/webm':['webm'],'video/ogg':['ogg','ogv']};
const MAX_IMAGE_BYTES=10*1024*1024,MAX_VIDEO_BYTES=100*1024*1024;const extensionOf=(n:string)=>{const i=n.lastIndexOf('.');return i>-1?n.slice(i+1).toLowerCase():''};const extensionMatches=(m:string,e:string)=>(IMAGE_EXTENSIONS[m]??VIDEO_EXTENSIONS[m]??[]).includes(e);
function hasValidSignature(b:Buffer,m:string){if(m==='image/png')return b.length>=8&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(m==='image/jpeg')return b.length>=3&&b.subarray(0,3).equals(Buffer.from([255,216,255]));if(m==='image/gif')return b.length>=6&&['GIF87a','GIF89a'].includes(b.subarray(0,6).toString('ascii'));if(m==='image/webp')return b.length>=12&&b.subarray(0,4).toString('ascii')==='RIFF'&&b.subarray(8,12).toString('ascii')==='WEBP';if(m==='video/webm')return b.length>=4&&b.subarray(0,4).equals(Buffer.from([26,69,223,163]));if(m==='video/ogg')return b.length>=4&&b.subarray(0,4).toString('ascii')==='OggS';if(m==='video/mp4')return b.length>=12&&b.subarray(4,8).toString('ascii')==='ftyp';return false;}
async function mediaUsage(u:string){if(!isDatabaseConfigured())return null;const p=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "Product" WHERE CAST("imagesJson" AS text) LIKE ${`%${u}%`} LIMIT 1`;if(p[0])return'product';const c=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "CategoryMeta" WHERE "imageUrl"=${u} LIMIT 1`;if(c[0])return'category';const b=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "Banner" WHERE "desktopImageUrl"=${u} OR "mobileImageUrl"=${u} LIMIT 1`;if(b[0])return'banner';const h=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "HomepageSection" WHERE CAST("configJson" AS text) LIKE ${`%${u}%`} LIMIT 1`;if(h[0])return'homepage';return null;}
const positiveInt=(v:string|null,f:number,m?:number)=>{const n=Number.parseInt(v??'',10);if(!Number.isFinite(n)||n<1)return f;return m===undefined?n:Math.min(m,n)};
export async function GET(req:NextRequest){const g=await requireAdminApi('media.manage');if(!g.ok)return g.response;try{return jsonOk(await listMediaAssets({q:req.nextUrl.searchParams.get('q')??undefined,kind:req.nextUrl.searchParams.get('kind')??undefined,page:positiveInt(req.nextUrl.searchParams.get('page'),1),pageSize:Math.max(10,positiveInt(req.nextUrl.searchParams.get('pageSize'),30,100))}));}catch{return jsonError('db_unavailable','Media library is unavailable',{status:503});}}
export async function POST(req:NextRequest){const g=await requireAdminApi('media.manage');if(!g.ok)return g.response;let uploadedUrl:string|null=null;try{const fd=await req.formData(),file=fd.get('file');if(!(file instanceof File))return jsonError('missing_file','File is required',{status:400});const isImage=IMAGE_TYPES.has(file.type),isVideo=VIDEO_TYPES.has(file.type);if(!isImage&&!isVideo)return jsonError('invalid_type','Unsupported media type',{status:400});if(isVideo&&!isPersistentStorageConfigured)return jsonError('video_storage_unavailable','Video storage is not configured',{status:503});const max=isVideo?MAX_VIDEO_BYTES:MAX_IMAGE_BYTES;if(file.size<=0||file.size>max)return jsonError('file_too_large',`Maximum size is ${isVideo?100:10} MB`,{status:400});if(!extensionMatches(file.type,extensionOf(file.name)))return jsonError('invalid_extension','File extension does not match its media type',{status:400});const header=Buffer.from(await file.slice(0,64).arrayBuffer());if(!hasValidSignature(header,file.type))return jsonError('invalid_signature','File contents do not match its media type',{status:400});const kind=isVideo?'video':'image',uploaded=await uploadPersistent(file,`admin/${kind}s`),secureUrl=uploaded.secure_url??null;if(!secureUrl)return jsonError('storage_no_url','Storage did not return a media URL',{status:502});uploadedUrl=secureUrl;const publicId=uploaded.public_id??null,dbFallback=publicId?.startsWith('db/')===true,id=dbFallback&&publicId?publicId.slice(3):await createMediaAsset({url:secureUrl,kind,mimeType:file.type,fileName:file.name,sizeBytes:file.size,folder:`admin/${kind}s`,createdById:g.user.id});if(dbFallback&&isDatabaseConfigured())await prisma.$executeRaw`UPDATE "MediaAsset" SET "createdById"=${g.user.id} WHERE "id"=${id}`;return jsonOk({id,url:secureUrl,kind,mimeType:file.type,fileName:file.name,sizeBytes:file.size},{status:201});}catch{if(uploadedUrl){try{await deletePersistent(uploadedUrl)}catch{}}return jsonError('upload_failed','Media upload failed',{status:500});}}
export async function DELETE(req:NextRequest){const g=await requireAdminApi('media.manage');if(!g.ok)return g.response;const id=req.nextUrl.searchParams.get('id');if(!id)return jsonError('invalid_id','Media id is required',{status:400});try{const rows=await prisma.$queryRaw<Array<{id:string;url:string}>>`SELECT "id","url" FROM "MediaAsset" WHERE "id"=${id} LIMIT 1`,asset=rows[0];if(!asset)return jsonError('not_found','Media not found',{status:404});const usage=await mediaUsage(asset.url);if(usage)return jsonError('media_in_use',`Media is still referenced by ${usage}`,{status:409});await deletePersistent(asset.url);if(!isInternalMediaUrl(asset.url))await deleteMediaAsset(id);return jsonOk({deleted:true});}catch{return jsonError('delete_failed','Media deletion failed',{status:500});}}
