import type { NextRequest } from 'next/server';
import { z } from 'zod';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import { requireSellerApi } from '@/lib/auth/require-seller-api';
import { jsonError, jsonOk } from '@/lib/api/response';
const schema=z.object({name:z.string().trim().min(2).max(120).optional(),slug:z.string().trim().min(2).max(120).optional(),description:z.string().trim().max(500).nullable().optional(),logoUrl:z.string().trim().max(500).nullable().optional(),isActive:z.boolean().optional()}).strict();
const slugify=(v:string)=>v.trim().toLowerCase().replace(/[^a-z0-9\u0600-\u06ff]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
async function owned(id:string,sellerId:string){const rows=await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "SellerBrand" WHERE "id"=${id} AND "sellerId"=${sellerId} LIMIT 1`;return rows[0];}
export async function GET(_:NextRequest,{params}:{params:Promise<{id:string}>}){const g=await requireSellerApi();if(!g.ok)return g.response;if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});const{id}=await params;try{const rows=await prisma.$queryRaw<Array<any>>`SELECT b."id",b."name",b."slug",b."description",b."logoUrl",b."isActive",b."createdAt",b."updatedAt",COUNT(p."id") AS "productCount" FROM "SellerBrand" b LEFT JOIN "Product" p ON p."brandId"=b."id" WHERE b."id"=${id} AND b."sellerId"=${g.user.id} GROUP BY b."id" LIMIT 1`;if(!rows[0])return jsonError('not_found','برند پیدا نشد.',{status:404});return jsonOk({...rows[0],productCount:Number(rows[0].productCount)});}catch{return jsonError('query_failed','خواندن برند ناموفق بود.',{status:500});}}
export async function PATCH(req:NextRequest,{params}:{params:Promise<{id:string}>}){const g=await requireSellerApi();if(!g.ok)return g.response;if(g.user.role==='admin')return jsonError('seller_context_required','Seller context required',{status:403});if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});const{id}=await params;if(!await owned(id,g.user.id))return jsonError('not_found','برند پیدا نشد.',{status:404});let body:unknown;try{body=await req.json()}catch{return jsonError('invalid_json','Invalid JSON',{status:400})};const p=schema.safeParse(body);if(!p.success)return jsonError('invalid_body','اطلاعات برند نامعتبر است.',{status:422});const sets:string[]=[];const vals:any[]=[];if(p.data.name!==undefined){sets.push('"name"');vals.push(p.data.name)}if(p.data.slug!==undefined){sets.push('"slug"');vals.push(slugify(p.data.slug))}if(p.data.description!==undefined){sets.push('"description"');vals.push(p.data.description)}if(p.data.logoUrl!==undefined){sets.push('"logoUrl"');vals.push(p.data.logoUrl)}if(p.data.isActive!==undefined){sets.push('"isActive"');vals.push(p.data.isActive)}if(!sets.length)return jsonError('nothing_to_update','تغییری ارسال نشده است.',{status:422});try{const q=sets.map((s,i)=>`${s}=$${i+1}`).join(',');const result=await prisma.$executeRawUnsafe(`UPDATE "SellerBrand" SET ${q}, "updatedAt"=NOW() WHERE "id"=$${vals.length+1} AND "sellerId"=$${vals.length+2}`,...vals,id,g.user.id);if(result!==1)return jsonError('not_found','برند پیدا نشد.',{status:404});return jsonOk({id,...p.data});}catch(e){if(String(e).toLowerCase().includes('duplicate'))return jsonError('duplicate','این slug قبلاً استفاده شده است.',{status:409});return jsonError('update_failed','ویرایش برند ناموفق بود.',{status:500});}}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){const g=await requireSellerApi();if(!g.ok)return g.response;if(g.user.role==='admin')return jsonError('seller_context_required','Seller context required',{status:403});if(!isDatabaseConfigured())return jsonError('db_unavailable','Database is not configured',{status:503});const{id}=await params;if(!await owned(id,g.user.id))return jsonError('not_found','برند پیدا نشد.',{status:404});try{await prisma.$executeRaw`UPDATE "SellerBrand" SET "isActive"=false,"updatedAt"=NOW() WHERE "id"=${id} AND "sellerId"=${g.user.id}`;return jsonOk({id,isActive:false});}catch{return jsonError('delete_failed','غیرفعال‌سازی برند ناموفق بود.',{status:500});}}
