import Image from 'next/image';
import { ArrowUpRight, BadgeCheck, Search, Tags, Store, Sparkles } from 'lucide-react';
import { setRequestLocale } from 'next-intl/server';
import { Prisma } from '@prisma/client';
import { prisma, isDatabaseConfigured } from '@/lib/db';
import { Link } from '@/i18n/routing';
import { Container } from '@/components/layout/container';
import { SiteHeader } from '@/features/home/components/site-header';
import { SiteFooter } from '@/features/home/components/site-footer';
import { BottomNavigation } from '@/features/home/components/bottom-navigation';

type Locale = 'fa' | 'ps' | 'en';
type BrandListItem = { id: string; slug: string; name: string; logoUrl: string | null; bannerUrl: string | null; shopName: string | null; sellerName: string; productCount: number };
const copy = {
  fa: { title: 'کشف برندها', subtitle: 'برندهای اختصاصی فروشگاه‌های تأییدشده را ببینید و مستقیم وارد دنیای محصولاتشان شوید.', placeholder: 'جستجوی نام برند یا فروشگاه…', badge: 'برند اختصاصی', store: 'فروشگاه', products: 'محصول', empty: 'برندی پیدا نشد.', unavailable: 'برندها فعلاً در دسترس نیستند.' },
  ps: { title: 'برانډونه ومومئ', subtitle: 'د تایید شوو پلورنځیو ځانګړي برانډونه وګورئ او د هغوی محصولاتو ته مستقیم لاړ شئ.', placeholder: 'د برانډ یا پلورنځي نوم ولټوئ…', badge: 'ځانګړی برانډ', store: 'پلورنځی', products: 'محصولات', empty: 'هیڅ برانډ ونه موندل شو.', unavailable: 'برانډونه اوس مهال شتون نه لري.' },
  en: { title: 'Discover brands', subtitle: 'Explore dedicated brands from verified stores and open each brand collection directly.', placeholder: 'Search a brand or store…', badge: 'Dedicated brand', store: 'Store', products: 'products', empty: 'No brand found.', unavailable: 'Brands are temporarily unavailable.' },
} as const;
export const dynamic = 'force-dynamic';

async function loadBrands(query: string): Promise<BrandListItem[] | null> {
  if (!isDatabaseConfigured()) return null;
  try {
    const q = query.trim(); const search = q ? Prisma.sql`AND (b."name" ILIKE ${`%${q}%`} OR u."sellerShopName" ILIKE ${`%${q}%`} OR u."fullName" ILIKE ${`%${q}%`})` : Prisma.empty;
    return await prisma.$queryRaw<BrandListItem[]>(Prisma.sql`SELECT b."id",b."slug",b."name",b."logoUrl",b."bannerUrl",u."sellerShopName" AS "shopName",u."fullName" AS "sellerName",(SELECT COUNT(*)::int FROM "Product" p WHERE p."brandId"=b."id" AND p."isActive"=true) AS "productCount" FROM "SellerBrand" b JOIN "User" u ON u."id"=b."sellerId" WHERE b."isActive"=true AND u."role"='seller' AND u."sellerStatus"='approved' AND u."isActive"=true ${search} ORDER BY b."name" ASC,b."createdAt" DESC LIMIT 48`);
  } catch (error) { console.error('[brands] DB error:', error); return null; }
}

export default async function BrandsPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ q?: string }> }) {
  const { locale: rawLocale } = await params; const locale = (['fa','ps','en'].includes(rawLocale) ? rawLocale : 'fa') as Locale; const { q='' } = await searchParams; setRequestLocale(locale); const t=copy[locale]; const brands=await loadBrands(q); const productLabel=t.products;
  return <div className="min-h-dvh bg-background"><SiteHeader/><main className="pb-20 md:pb-0">
    <section className="relative overflow-hidden border-b border-border bg-gradient-to-br from-primary/[0.12] via-background to-amber-50/40 py-12 dark:to-primary/[0.04] sm:py-16"><Container size="xl"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-xs font-black text-primary"><Sparkles className="h-3.5 w-3.5"/>{t.badge}</span><h1 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl">{t.title}</h1><p className="mt-4 max-w-2xl text-sm leading-8 text-muted-foreground sm:text-base">{t.subtitle}</p><form action={`/${locale}/brands`} method="get" className="mt-7 flex max-w-2xl items-center gap-2 rounded-2xl border border-border bg-card p-2 shadow-lg"><Search className="ms-2 h-5 w-5 shrink-0 text-muted-foreground"/><input name="q" defaultValue={q} placeholder={t.placeholder} className="min-w-0 flex-1 bg-transparent px-2 py-3 text-sm outline-none"/><button type="submit" className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white dark:bg-white dark:text-slate-950">{locale==='en'?'Search':locale==='ps'?'لټون':'جستجو'}</button></form></div></Container></section>
    <Container size="xl" className="py-8 sm:py-11">{!brands ? <div className="rounded-3xl border border-amber-400/30 bg-amber-50 p-14 text-center dark:bg-amber-950/20"><Tags className="mx-auto h-10 w-10 text-amber-600"/><h2 className="mt-4 font-black">{t.unavailable}</h2></div> : brands.length===0 ? <div className="rounded-3xl border border-dashed border-border p-14 text-center text-sm font-bold text-muted-foreground"><Tags className="mx-auto h-10 w-10 opacity-40"/><p className="mt-4">{t.empty}</p></div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{brands.map((brand)=><Link key={brand.id} href={`/brands/${brand.slug}` as never} className="group relative overflow-hidden rounded-[2rem] border border-border bg-card shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[1.65/1] overflow-hidden bg-muted">{brand.bannerUrl?<Image src={brand.bannerUrl} alt="" fill sizes="(max-width:640px) 100vw,(max-width:1024px) 50vw,25vw" className="object-cover transition duration-500 group-hover:scale-105"/>:<div className="h-full w-full bg-gradient-to-br from-primary/25 via-background to-amber-100/40 dark:to-primary/10"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent"/><span className="absolute start-3 top-3 inline-flex items-center gap-1 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-black text-slate-900"><BadgeCheck className="h-3 w-3 text-emerald-600"/>{t.badge}</span></div><div className="relative px-5 pb-5"><div className="-mt-10 flex items-end gap-3"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-3xl border-4 border-card bg-background shadow-lg">{brand.logoUrl?<Image src={brand.logoUrl} alt={brand.name} fill sizes="80px" className="object-cover"/>:<div className="flex h-full w-full items-center justify-center bg-primary text-2xl font-black text-primary-foreground">{brand.name.charAt(0)}</div>}</div><div className="min-w-0 pb-1"><h2 className="truncate text-lg font-black group-hover:text-primary">{brand.name}</h2><p className="mt-1 flex items-center gap-1 truncate text-[10px] text-muted-foreground"><Store className="h-3 w-3"/>{brand.shopName??brand.sellerName}</p></div></div><div className="mt-5 flex items-center justify-between gap-2"><span className="rounded-xl bg-muted px-3 py-2 text-[10px] font-bold">{brand.productCount.toLocaleString(locale==='en'?'en-US':locale==='ps'?'ps-AF':'fa-IR')} {productLabel}</span><span className="inline-flex items-center gap-1 text-xs font-black text-primary">{locale==='en'?'View brand':locale==='ps'?'برانډ وګورئ':'مشاهده برند'}<ArrowUpRight className="h-4 w-4 rtl:rotate-[-90deg] transition group-hover:-translate-y-0.5 group-hover:-translate-x-0.5"/></span></div></div></Link>)}</div>}</Container>
  </main><SiteFooter/><BottomNavigation/></div>;
}
