import { z } from 'zod';
import { isAllowedAdminMediaUrl } from '@/features/admin/lib/media-url';

export const PRODUCT_MAX_IMAGES = 12;
export const PRODUCT_MAX_IMAGE_BYTES = 20 * 1024 * 1024;
export const PRODUCT_IMAGE_MIME_TYPES = ['image/jpeg','image/png','image/webp','image/gif','image/avif','image/apng','image/svg+xml'] as const;
export function isProductImageMimeType(value: string): boolean { return value.startsWith('image/'); }
export function normalizePersianDigits(value: string): string { return value.replace(/[۰-۹]/g,(d)=>String(d.charCodeAt(0)-'۰'.charCodeAt(0))).replace(/[٠-٩]/g,(d)=>String(d.charCodeAt(0)-'٠'.charCodeAt(0))).replace(/٬/g,',').replace(/٫/g,'.'); }
function preprocessNumber(value: unknown): unknown { if(typeof value!=='string')return value;const normalized=normalizePersianDigits(value).replace(/,/g,'').trim();return normalized===''?undefined:Number(normalized); }
const positiveNumeric=z.preprocess(preprocessNumber,z.number().finite().positive('مقدار باید بیشتر از صفر باشد'));
const nonNegativeNumeric=z.preprocess(preprocessNumber,z.number().finite().min(0,'مقدار نمی‌تواند منفی باشد'));
const nonNegativeInteger=z.preprocess(preprocessNumber,z.number().int('مقدار باید عدد صحیح باشد').min(0,'مقدار نمی‌تواند منفی باشد'));
const mediaUrlSchema=z.string().trim().min(1).max(1000).refine(isAllowedAdminMediaUrl,'آدرس تصویر نامعتبر است');
const currencySchema=z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/,'واحد پول نامعتبر است');
export const productImagesSchema=z.array(mediaUrlSchema).max(PRODUCT_MAX_IMAGES);
const productWriteShape={slug:z.string().trim().max(120).nullable().optional(),name:z.string().trim().min(2,'نام محصول حداقل ۲ حرف باشد').max(120),shortDescription:z.string().trim().min(2,'توضیح کوتاه حداقل ۲ حرف باشد').max(300),description:z.string().trim().max(10000).nullable().optional(),price:positiveNumeric,currency:currencySchema.default('AFN'),categoryId:z.string().trim().min(1,'انتخاب دسته‌بندی الزامی است'),region:z.string().trim().min(1,'کشور یا منطقه الزامی است').max(120).default('افغانستان'),badge:z.string().trim().max(40).nullable().optional(),inStock:z.boolean().default(true),stockQuantity:nonNegativeInteger.default(0),images:productImagesSchema.default([]),primaryImageIndex:nonNegativeInteger.default(0),compareAtPrice:positiveNumeric.nullable().optional(),isActive:z.boolean().default(true),whatsappNumber:z.string().trim().max(40).nullable().optional(),videoUrl:z.string().trim().max(500).nullable().optional(),isTraditional:z.boolean().default(false),weightKg:nonNegativeNumeric.nullable().optional(),dimensionsJson:z.string().max(200).nullable().optional(),tagsJson:z.string().max(500).nullable().optional(),attributesJson:z.string().max(2000).nullable().optional()} satisfies z.ZodRawShape;
const productWriteSchema=z.object(productWriteShape);
export const productCreateSchema=productWriteSchema.superRefine((value,ctx)=>{if(value.images.length===0&&value.primaryImageIndex!==0)ctx.addIssue({code:z.ZodIssueCode.custom,path:['primaryImageIndex'],message:'وقتی تصویر ندارید، شاخص تصویر اصلی باید صفر باشد'});if(value.images.length>0&&value.primaryImageIndex>=value.images.length)ctx.addIssue({code:z.ZodIssueCode.custom,path:['primaryImageIndex'],message:'تصویر اصلی انتخاب‌شده معتبر نیست'});if(value.compareAtPrice!==null&&value.compareAtPrice!==undefined&&value.compareAtPrice<=value.price)ctx.addIssue({code:z.ZodIssueCode.custom,path:['compareAtPrice'],message:'قیمت قبلی باید از قیمت فعلی بیشتر باشد'});});
export const productUpdateSchema=productWriteSchema.partial().strict().superRefine((value,ctx)=>{if(value.images===undefined||value.primaryImageIndex===undefined)return;if(value.images.length===0&&value.primaryImageIndex!==0)ctx.addIssue({code:z.ZodIssueCode.custom,path:['primaryImageIndex'],message:'وقتی تصویر ندارید، شاخص تصویر اصلی باید صفر باشد'});if(value.images.length>0&&value.primaryImageIndex>=value.images.length)ctx.addIssue({code:z.ZodIssueCode.custom,path:['primaryImageIndex'],message:'تصویر اصلی انتخاب‌شده معتبر نیست'});});
export type ProductCreateInput=z.infer<typeof productCreateSchema>;export type ProductUpdateInput=z.infer<typeof productUpdateSchema>;
export function parseProductImages(raw:unknown):string[]{if(raw==null)return[];let value:unknown=raw;if(typeof raw==='string'){try{value=JSON.parse(raw)as unknown}catch{return[]}}if(!Array.isArray(value))return[];return value.map((item)=>{if(typeof item==='string')return item;if(item&&typeof item==='object'&&'src'in item){const src=(item as {src?:unknown}).src;return typeof src==='string'?src:''}if(item&&typeof item==='object'&&'url'in item){const url=(item as {url?:unknown}).url;return typeof url==='string'?url:''}return''}).filter((url):url is string=>url.trim().length>0).slice(0,PRODUCT_MAX_IMAGES)}
export const PRODUCT_VALIDATION_LABELS:Record<string,string>={name:'نام محصول',shortDescription:'توضیح کوتاه',price:'قیمت',currency:'واحد پول',categoryId:'دسته‌بندی',region:'منطقه',stockQuantity:'موجودی',images:'تصاویر',primaryImageIndex:'تصویر اصلی',compareAtPrice:'قیمت قبلی'};
export function productValidationMessage(issues:z.ZodIssue[]):string{const first=issues[0];if(!first)return'اطلاعات محصول معتبر نیست.';const key=String(first.path[0]??'');const label=PRODUCT_VALIDATION_LABELS[key]??'اطلاعات محصول';return`${label}: ${first.message}`;}
